/* AIF-C01 flashcard dataset — parsed from the memorization sheet.
   Each card: { id, cat, front, back, quiz?, tag?, use?, example? }
   quiz:true → eligible for multiple-choice quiz mode
   use      → concise "purpose / why it matters", revealed by the Show purpose button
   example  → a typical real-world situation it applies to, revealed by the Show example button */

export const data = (function () {
  const categories = [
    { id: 'services', name: 'AWS Services',     short: 'Services',  hue: 188, blurb: 'What does each service do? — the #1 question pattern.' },
    { id: 'acronyms', name: 'Acronyms',         short: 'Acronyms',  hue: 286, blurb: 'Decode every abbreviation cold.' },
    { id: 'concepts', name: 'Core Concepts',    short: 'Concepts',  hue: 150, blurb: 'Learning types, metrics, the customization ladder.' },
    { id: 'patterns', name: 'Question Patterns', short: 'Patterns', hue: 24,  blurb: 'Scenario → answer. Train the reflex.' },
  ];

  const c = (id, cat, front, back, extra = {}) => ({ id, cat, front, back, ...extra });

  const cards = [
    // ───────────────── ACRONYMS ─────────────────
    c('a1',  'acronyms', 'AI',        'Artificial Intelligence', { quiz: true, use: 'Umbrella field for machines performing human-like tasks.', example: 'A bank flags unusual card transactions for fraud in real time.' }),
    c('a2',  'acronyms', 'ML',        'Machine Learning', { quiz: true, use: 'Systems that learn patterns from data instead of explicit rules.', example: 'An email service learns to filter spam from millions of past examples.' }),
    c('a3',  'acronyms', 'DL',        'Deep Learning', { quiz: true, use: 'ML using multi-layer neural networks for complex patterns.', example: 'A photo app recognises faces and objects using neural networks.' }),
    c('a4',  'acronyms', 'NLP',       'Natural Language Processing', { quiz: true, use: 'Lets computers understand and generate human language.', example: 'A helpdesk auto-tags support tickets by reading their text.' }),
    c('a5',  'acronyms', 'LLM',       'Large Language Model', { quiz: true, use: 'Generates and understands text; powers chatbots and assistants.', example: 'A chatbot drafts natural written replies to customer questions.' }),
    c('a6',  'acronyms', 'GenAI',     'Generative AI', { quiz: true, use: 'Creates new content — text, images, code — from a prompt.', example: 'A marketer generates draft ad copy and images from a short prompt.' }),
    c('a7',  'acronyms', 'FM',        'Foundation Model', { quiz: true, use: 'Large pre-trained model adapted to many downstream tasks.', example: 'One pre-trained model powers a summariser, a chatbot and a classifier.' }),
    c('a8',  'acronyms', 'RAG',       'Retrieval Augmented Generation', { quiz: true, use: 'Grounds an FM in your own data to reduce hallucination — no training.', example: 'A chatbot answers HR questions from the current staff handbook, untrained.' }),
    c('a9',  'acronyms', 'MCP',       'Model Context Protocol — connects agents to external systems', { quiz: true, use: 'Standard way to connect AI agents to external tools and data.', example: 'A coding agent reads your Jira tickets and queries your database via MCP.' }),
    c('a10', 'acronyms', 'MLOps',     'Machine Learning Operations', { quiz: true, use: 'Practices to deploy, monitor and maintain ML in production.', example: 'A team auto-retrains and redeploys a model when its accuracy drifts.' }),
    c('a11', 'acronyms', 'RLHF',      'Reinforcement Learning from Human Feedback', { quiz: true, use: 'Aligns model output to human preferences during training.', example: 'An assistant is tuned so its answers match what human reviewers prefer.' }),
    c('a12', 'acronyms', 'ROUGE',     'Recall-Oriented Understudy for Gisting Evaluation — text summarization metric', { quiz: true, use: 'Scores summary quality by overlap with a reference.', example: 'Checking whether a news summariser captures the article key points.' }),
    c('a13', 'acronyms', 'BLEU',      'Bilingual Evaluation Understudy — translation metric', { quiz: true, use: 'Scores machine-translation quality against a reference.', example: 'Scoring how close machine translation is to a human reference.' }),
    c('a14', 'acronyms', 'BERTScore', 'Semantic similarity metric for generated text', { quiz: true, use: 'Judges generated text by meaning, not exact word overlap.', example: 'Judging a paraphrase as correct even when it uses different words.' }),
    c('a15', 'acronyms', 'ROI',       'Return on Investment', { quiz: true, use: 'Measures the business value of an AI project versus its cost.', example: 'Deciding whether a support chatbot saved enough cost to justify it.' }),
    c('a16', 'acronyms', 'F1 score',  'Harmonic mean of precision and recall', { quiz: true, use: 'Balances precision and recall — good for imbalanced classes.', example: 'Grading a fraud detector where real fraud is rare and imbalanced.' }),
    c('a17', 'acronyms', 'A2I',       'Amazon Augmented AI — human-in-the-loop review', { quiz: true, use: 'Routes low-confidence ML predictions to humans for review.', example: 'Low-confidence document extractions are routed to a human reviewer.' }),
    c('a18', 'acronyms', 'IAM',       'Identity and Access Management', { quiz: true, use: 'Controls who can access which AWS resources.', example: 'Granting an analyst read-only access to a single S3 bucket.' }),
    c('a19', 'acronyms', 'KMS',       'Key Management Service — encryption keys', { quiz: true, use: 'Creates and manages encryption keys to protect data.', example: 'Encrypting customer records in S3 with a tightly controlled key.' }),

    // ───────────────── SERVICES ─────────────────
    // Managed AI services
    c('s1',  'services', 'Amazon Comprehend',   'NLP — sentiment, entities, key phrases, PII detection', { quiz: true, tag: 'Managed AI', use: 'Reach for it to mine sentiment or PII from raw text.', example: 'A retailer scans thousands of product reviews to flag negative sentiment.' }),
    c('s2',  'services', 'Amazon Transcribe',   'Speech → text', { quiz: true, tag: 'Managed AI', use: 'Use it to caption calls, meetings or voice notes.', example: 'A call centre turns recorded support calls into searchable transcripts.' }),
    c('s3',  'services', 'Amazon Translate',    'Language translation', { quiz: true, tag: 'Managed AI', use: 'Localize app content or chat across languages.', example: 'Help-centre articles are translated into a dozen languages automatically.' }),
    c('s4',  'services', 'Amazon Polly',        'Text → speech (voice)', { quiz: true, tag: 'Managed AI', use: 'Give apps a spoken voice — IVR, audiobooks, accessibility.', example: 'An app reads articles aloud and voices an IVR phone menu.' }),
    c('s5',  'services', 'Amazon Lex',          'Chatbots / conversational voice & text interfaces', { quiz: true, tag: 'Managed AI', use: 'The bot brain behind Alexa-style chat and voice apps.', example: 'The conversational bot behind a "track my order" phone line.' }),
    c('s6',  'services', 'Amazon Rekognition',  'Image & video analysis (computer vision)', { quiz: true, tag: 'Managed AI', use: 'Detect objects, faces or moderation issues in media.', example: 'A platform auto-moderates user-uploaded photos for unsafe content.' }),
    c('s7',  'services', 'Amazon Textract',     'Extract text & data from scanned documents (OCR)', { quiz: true, tag: 'Managed AI', use: 'Pull fields from invoices, forms and IDs — beyond plain OCR.', example: 'Pulling line items and totals from scanned supplier invoices.' }),
    c('s8',  'services', 'Amazon Kendra',       'Intelligent enterprise search', { quiz: true, tag: 'Managed AI', use: 'Add natural-language search across your documents.', example: 'Staff ask a search box natural questions and get answers from internal PDFs.' }),
    c('s9',  'services', 'Amazon Personalize',  'Recommendation systems', { quiz: true, tag: 'Managed AI', use: 'The same tech behind Amazon.com "recommended for you".', example: 'Powering a "recommended for you" carousel on an online store.' }),
    c('s10', 'services', 'Amazon A2I',          'Human review of ML predictions (human-in-the-loop)', { quiz: true, tag: 'Managed AI', use: 'Add a human checkpoint when ML confidence is low.', example: 'Low-confidence invoice fields go to a reviewer before being accepted.' }),
    // GenAI / FM platform
    c('s11', 'services', 'Amazon Bedrock',                   'Managed access to foundation models via API — the central GenAI service', { quiz: true, tag: 'GenAI / FM', use: 'The exam’s default answer for "use FMs via API".', example: 'Adding a GenAI feature by calling Claude or Nova through one API.' }),
    c('s12', 'services', 'Bedrock Knowledge Bases',          'RAG — ground FMs in your own data', { quiz: true, tag: 'GenAI / FM', use: 'The managed way to do RAG on Bedrock.', example: 'A support bot answers from your own product docs without fine-tuning.' }),
    c('s13', 'services', 'Bedrock Guardrails',               'Content filtering & safety — block harmful / toxic output', { quiz: true, tag: 'GenAI / FM', use: 'The answer for "block toxic or unsafe FM output".', example: 'Stopping a customer chatbot from returning hateful or unsafe replies.' }),
    c('s14', 'services', 'Bedrock Model Evaluation',         'Evaluate & compare FM performance', { quiz: true, tag: 'GenAI / FM', use: 'Compare models to pick the best for your task.', example: 'Comparing two models on your own prompts to pick the more accurate one.' }),
    c('s15', 'services', 'Bedrock Prompt Management',        'Prompt versioning & management', { quiz: true, tag: 'GenAI / FM', use: 'Version and reuse prompts like source code.', example: 'Versioning and A/B-testing prompt variants across a team.' }),
    c('s16', 'services', 'Bedrock AgentCore',                'Build & run AI agents (incl. AgentCore Identity, Policy)', { quiz: true, tag: 'GenAI / FM', use: 'Run multi-step agents that call tools securely.', example: 'Running a support agent that securely calls internal APIs at scale.' }),
    c('s17', 'services', 'Amazon Nova',                      'Amazon’s own family of foundation models', { quiz: true, tag: 'GenAI / FM', use: 'Amazon’s first-party FMs offered inside Bedrock.', example: 'Using Amazon’s low-cost multimodal model in Bedrock for text and images.' }),
    c('s18', 'services', 'Amazon Q',                         'AWS generative AI assistant', { quiz: true, tag: 'GenAI / FM', use: 'AWS’s built-in GenAI helper for code and the console.', example: 'Asking an in-IDE assistant to explain code or query company data in plain English.' }),
    // SageMaker
    c('s19', 'services', 'Amazon SageMaker AI',     'Build, train & deploy ML models', { quiz: true, tag: 'SageMaker', use: 'Pick it when you build custom models, not just use FMs.', example: 'A data team trains a custom demand-forecasting model on its own data.' }),
    c('s20', 'services', 'SageMaker JumpStart',     'Pre-trained models / FM hub', { quiz: true, tag: 'SageMaker', use: 'Start from a pre-trained model instead of scratch.', example: 'Deploying a pre-trained image classifier instead of training from scratch.' }),
    c('s21', 'services', 'SageMaker Clarify',       'Bias detection + explainability', { quiz: true, tag: 'SageMaker', use: 'The answer for "detect bias" or "explain a prediction".', example: 'Checking a loan model for bias and explaining its decisions.' }),
    c('s22', 'services', 'SageMaker Model Monitor', 'Monitor models in production (drift)', { quiz: true, tag: 'SageMaker', use: 'Catch data or quality drift after deployment.', example: 'Alerting when a live model’s input data drifts from its training data.' }),
    c('s23', 'services', 'SageMaker Model Cards',   'Document model details — transparency & data lineage', { quiz: true, tag: 'SageMaker', use: 'The answer for "document model lineage & details".', example: 'Documenting a model’s training data and intended use for auditors.' }),
    // Security / governance
    c('s24', 'services', 'AWS IAM',             'Roles, policies, permissions — access control', { quiz: true, tag: 'Security', use: 'First line of access control for every AWS resource.', example: 'Letting a Lambda function write to just one DynamoDB table.' }),
    c('s25', 'services', 'AWS KMS',             'Encryption key management', { quiz: true, tag: 'Security', use: 'The answer for "manage encryption keys".', example: 'Managing the keys that encrypt data in S3, EBS and RDS.' }),
    c('s26', 'services', 'Amazon Macie',        'Discover & protect sensitive data (PII) in S3', { quiz: true, tag: 'Security', use: 'The answer for "find PII sitting in S3".', example: 'Scanning S3 buckets to find exposed credit-card or PII data.' }),
    c('s27', 'services', 'AWS PrivateLink',     'Private connectivity — no public internet', { quiz: true, tag: 'Security', use: 'Keep service traffic off the public internet.', example: 'Reaching an AWS service from your VPC without using the public internet.' }),
    c('s28', 'services', 'AWS CloudTrail',      'Audit log of API activity', { quiz: true, tag: 'Security', use: 'The answer for "audit who called which API".', example: 'Finding out which user deleted an S3 bucket and when.' }),
    c('s29', 'services', 'Amazon CloudWatch',   'Monitoring & metrics', { quiz: true, tag: 'Security', use: 'Metrics, logs and alarms for your workloads.', example: 'Alarming when an API error rate or server CPU crosses a threshold.' }),
    c('s30', 'services', 'AWS Config',          'Resource configuration compliance', { quiz: true, tag: 'Security', use: 'Track and flag resource configuration changes.', example: 'Flagging any S3 bucket that becomes publicly readable.' }),
    c('s31', 'services', 'AWS Audit Manager',   'Automate compliance audits', { quiz: true, tag: 'Security', use: 'Automate evidence collection for audits.', example: 'Continuously collecting evidence for a SOC 2 or PCI audit.' }),
    c('s32', 'services', 'AWS Artifact',        'On-demand compliance reports', { quiz: true, tag: 'Security', use: 'Self-serve AWS compliance reports (SOC, ISO…).', example: 'Downloading AWS’s SOC 2 or ISO report for your auditor.' }),
    c('s33', 'services', 'Amazon Inspector',    'Vulnerability scanning', { quiz: true, tag: 'Security', use: 'Scan workloads for known vulnerabilities.', example: 'Automatically scanning EC2 instances and images for known CVEs.' }),
    c('s34', 'services', 'AWS Trusted Advisor', 'Best-practice recommendations', { quiz: true, tag: 'Security', use: 'Automated best-practice checks across your account.', example: 'Being flagged for idle resources, open ports and missing MFA.' }),
    // Extra reference
    c('s35', 'services', 'Vector databases for embeddings', 'OpenSearch Service, Aurora, Neptune, RDS for PostgreSQL', { tag: 'Reference', use: 'Where embeddings are stored so RAG can search them.', example: 'Storing document embeddings so a RAG chatbot can search them.' }),

    // ───────────────── CORE CONCEPTS ─────────────────
    c('k1',  'concepts', 'The AI → ML → DL hierarchy', 'AI ⊃ ML ⊃ Deep Learning. GenAI is a subset of DL that uses Foundation Models.', { use: 'Know the nesting: GenAI sits inside DL, inside ML, inside AI.', example: 'Explaining to stakeholders where GenAI sits when scoping a project.' }),
    c('k2',  'concepts', 'Agentic AI', 'Autonomous, multi-step, tool-using systems', { use: 'The "autonomous, tool-using" buzzword on the newer exam.', example: 'An assistant books travel itself, searching and calling APIs across steps.' }),
    c('k3',  'concepts', 'Supervised learning', 'Labeled data → classification & regression', { use: 'If the scenario gives labeled data, pick this.', example: 'Predicting house prices from labelled past sales.' }),
    c('k4',  'concepts', 'Unsupervised learning', 'Unlabeled data → clustering', { use: 'No labels and you want groupings? Pick this.', example: 'Grouping customers into segments with no predefined labels.' }),
    c('k5',  'concepts', 'Reinforcement learning', 'Reward / penalty feedback (RLHF for FMs)', { use: 'Trial-and-error with rewards — also how RLHF works.', example: 'Training a game agent to improve through rewards and penalties.' }),
    c('k6',  'concepts', 'Inference types', 'Batch, real-time, asynchronous, serverless', { use: 'Match latency and throughput needs to the right mode.', example: 'Real-time inference for a live chatbot; batch for overnight scoring.' }),
    c('k7',  'concepts', 'Regression', 'Predict a number (continuous value)', { use: 'Use when the target is a quantity, like price or temperature.', example: 'Forecasting tomorrow’s sales figure, a continuous number.' }),
    c('k8',  'concepts', 'Classification', 'Predict a category', { use: 'Use when the target is a label, like spam vs. not-spam.', example: 'Deciding whether an email is spam or not, a category.' }),
    c('k9',  'concepts', 'Clustering', 'Group similar items (unsupervised)', { use: 'Use to find segments when you have no labels.', example: 'Discovering natural customer segments from purchase history.' }),
    c('k10', 'concepts', 'High bias leads to…?', 'Underfitting — the model is too simple', { use: 'Fix by adding features or using a richer model.', example: 'A too-simple model that misses patterns in both training and test data.' }),
    c('k11', 'concepts', 'High variance leads to…?', 'Overfitting — the model memorizes the training data', { use: 'Fix by adding data or regularization.', example: 'A model that aces training data but fails on new, unseen data.' }),
    c('k12', 'concepts', 'Classification metrics', 'Accuracy, precision, recall, F1', { use: 'How you grade a classifier’s correctness.', example: 'Reporting accuracy, precision, recall and F1 for a disease detector.' }),
    c('k13', 'concepts', 'Text-generation metrics', 'ROUGE (summaries), BLEU (translation), BERTScore, LLM-as-a-judge', { use: 'How you grade what an LLM writes.', example: 'Scoring a summariser with ROUGE and a translator with BLEU.' }),
    c('k14', 'concepts', 'Business metrics', 'ROI, cost per user, customer lifetime value, conversion rate', { use: 'Tie an AI project back to dollars and outcomes.', example: 'Justifying an AI project to leadership using ROI and conversion rate.' }),
    c('k15', 'concepts', 'GenAI building blocks', 'Tokens, embeddings, vectors, chunking, transformers, diffusion models, multi-modal models', { use: 'The vocabulary the exam expects you to recognize.', example: 'Why long documents are chunked and embedded for a RAG system.' }),
    c('k16', 'concepts', 'Temperature', 'Higher = more random / creative; lower = more deterministic / focused', { use: 'Turn it up for creativity, down for consistency.', example: 'Low temperature for a factual Q&A bot; high for brainstorming taglines.' }),
    c('k17', 'concepts', 'Prompt engineering techniques', 'Zero-shot, single-shot, few-shot, chain-of-thought, prompt templates, negative prompts', { use: 'The cheapest lever to improve an FM’s output.', example: 'Adding a few worked examples so an FM replies in the right format.' }),
    c('k18', 'concepts', 'Prompt risks', 'Prompt injection, jailbreaking, poisoning, hijacking, exposure', { use: 'Security threats unique to prompts and LLMs.', example: 'Hardening a chatbot against a user trying to override its instructions.' }),
    c('k19', 'concepts', 'FM customization ladder (cheap → expensive)', '1) Prompt engineering  2) RAG  3) Fine-tuning  4) Continued pre-training  5) Pre-train from scratch', { use: 'Climb only as high as the task needs — cost rises fast.', example: 'Trying prompts and RAG before paying to fine-tune a model.' }),
    c('k20', 'concepts', 'What is RAG?', 'Retrieves external data to ground the FM in facts; reduces hallucination — no model training', { use: 'Best "reduce hallucination with our data" answer.', example: 'Making a bot cite your current policy docs instead of guessing.' }),
    c('k21', 'concepts', 'Fine-tuning methods', 'Instruction tuning, domain adaptation, transfer learning, continued pre-training, RLHF', { use: 'Ways to adapt a model when prompting isn’t enough.', example: 'Adapting an FM to your legal domain’s language and terms.' }),
    c('k22', 'concepts', 'Responsible AI pillars', 'Fairness, bias mitigation, inclusivity, robustness, safety, veracity (truthfulness)', { use: 'The values AWS expects you to be able to name.', example: 'Reviewing an AI feature for fairness and safety before launch.' }),
    c('k23', 'concepts', 'Transparency vs. explainability', 'Transparent = see HOW it works (Model Cards). Explainable = understand WHY it decided (Clarify).', { use: 'Two different "understandability" ideas — don’t mix them up.', example: 'Model Cards show how a model works; Clarify explains a single decision.' }),
    c('k24', 'concepts', 'Hallucination mitigation', 'RAG grounding, output validation, confidence scoring', { use: 'Tactics to keep FM answers truthful.', example: 'Grounding answers with RAG so a bot stops inventing facts.' }),
    c('k25', 'concepts', 'Shared responsibility model', 'AWS secures the cloud (infrastructure); the customer secures in the cloud (data, access, config)', { use: 'Know which side secures what — a frequent question.', example: 'AWS patches the hardware while you secure your data and IAM.' }),
    c('k26', 'concepts', 'Generative AI Security Scoping Matrix', 'The governance framework to know by name', { use: 'Name-drop this for GenAI security/governance questions.', example: 'Classifying a GenAI app’s risk to decide what controls it needs.' }),

    // ───────────────── QUESTION PATTERNS ─────────────────
    c('p1',  'patterns', 'Need to transcribe audio to text?', 'Amazon Transcribe', { use: 'Trigger words: audio, voice, call → text.', example: 'Generating written minutes from a recorded meeting.' }),
    c('p2',  'patterns', 'Need to translate between languages?', 'Amazon Translate', { use: 'Trigger word: between languages.', example: 'Showing a product page in each visitor’s own language.' }),
    c('p3',  'patterns', 'Need to build a chatbot?', 'Amazon Lex', { use: 'Trigger words: conversational bot, voice or text.', example: 'A "track my order" assistant on a retail website.' }),
    c('p4',  'patterns', 'Need to analyze images or video?', 'Amazon Rekognition', { use: 'Trigger words: images, video, faces, objects.', example: 'Auto-moderating user-uploaded photos for unsafe content.' }),
    c('p5',  'patterns', 'Need to extract text from scanned docs?', 'Amazon Textract', { use: 'Trigger words: scanned documents, forms, invoices.', example: 'Reading the totals off scanned receipts.' }),
    c('p6',  'patterns', 'Need sentiment analysis on text?', 'Amazon Comprehend', { use: 'Trigger words: sentiment, entities, PII in text.', example: 'Gauging mood across thousands of survey responses.' }),
    c('p7',  'patterns', 'Need to access foundation models via API?', 'Amazon Bedrock', { use: 'Trigger words: foundation models, via API.', example: 'Adding a "summarise this" button backed by an LLM.' }),
    c('p8',  'patterns', 'Need to ground answers in company docs?', 'RAG (Bedrock Knowledge Bases)', { use: 'Trigger words: reduce hallucination, use our own data.', example: 'A helpdesk bot that answers from your internal wiki.' }),
    c('p9',  'patterns', 'Cheapest / least-effort way to customize an FM?', 'Prompt engineering / in-context learning', { use: 'Trigger words: cheapest, fastest, least effort.', example: 'Improving answers just by rewriting the prompt.' }),
    c('p10', 'patterns', 'Need to bake domain knowledge into the model?', 'Fine-tuning (or continued pre-training)', { use: 'Trigger words: bake in knowledge, change the model itself.', example: 'Teaching a model your product catalogue and house tone.' }),
    c('p11', 'patterns', 'Traditional ML or an FM — how to choose?', 'Regulatory / explainability needs → traditional ML. Flexible content generation → FM.', { use: 'Decide by explainability vs. flexible generation.', example: 'A regulated credit decision versus writing marketing copy.' }),
    c('p12', 'patterns', 'Need to detect bias or explain predictions?', 'SageMaker Clarify', { use: 'Trigger words: bias, fairness, explainability.', example: 'Auditing a hiring model for fairness.' }),
    c('p13', 'patterns', 'Need to filter harmful or toxic output?', 'Bedrock Guardrails', { use: 'Trigger words: block harmful, toxic, unsafe output.', example: 'Stopping a public chatbot from returning toxic text.' }),
    c('p14', 'patterns', 'How do you choose the learning type?', 'Labeled data → supervised. Unlabeled → unsupervised. Reward signal → reinforcement.', { use: 'Read the data: labels, no labels, or rewards.', example: 'Labelled photos point to supervised; unlabelled logs to unsupervised.' }),
    c('p15', 'patterns', 'What does raising temperature do?', 'Makes output more creative / random', { use: 'Higher temperature = more randomness; lower = more focused.', example: 'Turning temperature up to brainstorm varied slogans.' }),
    c('p16', 'patterns', 'Where do you store embeddings?', 'A vector DB: OpenSearch / Aurora / Neptune / RDS for PostgreSQL', { use: 'Trigger words: embeddings, vector search.', example: 'Holding document vectors so a RAG app can search them.' }),
    c('p17', 'patterns', 'Need to document model lineage & details?', 'SageMaker Model Cards', { use: 'Trigger words: lineage, transparency, model documentation.', example: 'Recording a model’s training data and intended use for an audit.' }),
    c('p18', 'patterns', 'Need to audit API activity?', 'AWS CloudTrail', { use: 'Trigger words: audit, who did what, API calls.', example: 'Finding out who changed a security group last week.' }),

    // ═══════════════ EXPANSION ═══════════════
    // Net-new cards covering the current exam guide. Each carries an explicit
    // `diff`. Cards tagged "Beyond guide" are services the latest guide moved
    // out of its in-scope list but that still appear in practice questions.

    // ───────────────── ACRONYMS (new) ─────────────────
    c('a20', 'acronyms', 'CoT',  'Chain-of-Thought — prompt the model to reason step by step', { diff: 'easy', use: 'A prompting technique that elicits intermediate reasoning.', example: 'Asking a model to "think step by step" before giving a final answer.' }),
    c('a21', 'acronyms', 'HITL', 'Human-in-the-Loop', { diff: 'easy', use: 'A person reviews or approves model output in the workflow.', example: 'A reviewer checks low-confidence document extractions before they are saved.' }),
    c('a22', 'acronyms', 'PII',  'Personally Identifiable Information', { diff: 'easy', use: 'Sensitive personal data that must be protected and can be redacted.', example: 'Names, emails and card numbers found in support transcripts.' }),
    c('a23', 'acronyms', 'OCR',  'Optical Character Recognition', { diff: 'easy', use: 'Turns text in images and scans into machine-readable text.', example: 'Reading the printed numbers off a scanned invoice.' }),
    c('a24', 'acronyms', 'ETL',  'Extract, Transform, Load', { diff: 'easy', use: 'The pipeline that prepares raw data for analysis or training.', example: 'AWS Glue extracting, cleaning and loading data into a warehouse.' }),
    c('a25', 'acronyms', 'ARPU', 'Average Revenue Per User', { diff: 'easy', use: 'A business metric for the value an AI feature drives per user.', example: 'Measuring whether an AI upsell raised revenue per customer.' }),
    c('a26', 'acronyms', 'CLV',  'Customer Lifetime Value', { diff: 'easy', use: 'Total expected revenue from a customer — a GenAI business metric.', example: 'Justifying a personalisation feature by its lift in lifetime value.' }),
    c('a27', 'acronyms', 'EC2',  'Elastic Compute Cloud — virtual servers', { diff: 'easy', use: 'Resizable compute capacity in the cloud.', example: 'Hosting a self-managed model inference server.' }),
    c('a28', 'acronyms', 'S3',   'Simple Storage Service — object storage', { diff: 'easy', use: 'Durable object storage for datasets, models and documents.', example: 'Holding the training data and model artefacts for an ML project.' }),
    c('a29', 'acronyms', 'VPC',  'Virtual Private Cloud — isolated private network', { diff: 'easy', use: 'A logically isolated network for your AWS resources.', example: 'Running inference endpoints without exposing them to the internet.' }),
    c('a30', 'acronyms', 'RDS',  'Relational Database Service', { diff: 'easy', use: 'Managed relational databases; some engines store vector embeddings.', example: 'RDS for PostgreSQL holding embeddings for a RAG app.' }),

    // ───────────────── SERVICES — GenAI / developer (in scope) ─────────────────
    c('s36', 'services', 'Amazon Q Developer', 'AI coding assistant — code generation, in-IDE help, security scans', { diff: 'easy', tag: 'GenAI / FM', use: 'AWS’s GenAI assistant for software development.', example: 'Generating a function and flagging vulnerabilities inside the IDE.' }),
    c('s37', 'services', 'Amazon Q Business', 'GenAI assistant that answers from your enterprise data with citations', { diff: 'easy', tag: 'GenAI / FM', use: 'A permissions-aware assistant over company documents and apps.', example: 'Staff ask plain-English questions and get cited answers from internal data.' }),
    c('s38', 'services', 'Amazon Quick Suite', 'Business intelligence with dashboards and AI analytics agents', { diff: 'intermediate', tag: 'GenAI / FM', use: 'Unified BI plus AI-powered analytics and automated workflows.', example: 'Asking a dashboard a question in natural language to get an insight.' }),
    c('s39', 'services', 'Kiro', 'Agentic AI IDE — spec-driven development with hooks', { diff: 'intermediate', tag: 'GenAI / FM', use: 'An AI IDE that turns specs into code, tests and tasks.', example: 'Describing a feature and letting the IDE plan and generate the code.' }),
    c('s40', 'services', 'Strands Agents', 'Open-source SDK for building autonomous AI agents', { diff: 'intermediate', tag: 'GenAI / FM', use: 'Code-first framework for agents that use tools, memory and models.', example: 'Building an agent that calls AWS APIs and an FM to complete a task.' }),
    c('s41', 'services', 'AWS Transform', 'Agentic AI service for modernising and migrating workloads', { diff: 'intermediate', tag: 'GenAI / FM', use: 'Automates mainframe, VMware and .NET modernisation with human review.', example: 'Converting legacy mainframe code into modern Java microservices.' }),
    c('s42', 'services', 'Bedrock AgentCore Runtime', 'Serverless runtime to deploy and scale AI agents', { diff: 'intermediate', tag: 'GenAI / FM', use: 'Run agents securely in production without managing infrastructure.', example: 'Hosting a customer-support agent that scales with demand.' }),
    c('s43', 'services', 'Bedrock AgentCore Memory', 'Short- and long-term memory for AI agents', { diff: 'intermediate', tag: 'GenAI / FM', use: 'Lets an agent remember context across turns and sessions.', example: 'A support agent recalling a customer’s earlier issue in a later chat.' }),
    c('s44', 'services', 'Bedrock AgentCore Identity', 'Secure agent access to tools and AWS resources', { diff: 'intermediate', tag: 'GenAI / FM', use: 'Identity and access controls for what an agent may call.', example: 'Allowing an agent to query one database but not delete records.' }),
    c('s45', 'services', 'Bedrock Model Distillation', 'Transfer a large teacher model’s knowledge into a smaller student model', { diff: 'advanced', tag: 'GenAI / FM', use: 'Get near-teacher quality at lower cost and latency.', example: 'Distilling a large model into a small one for cheap high-volume calls.' }),

    // ───────────────── SERVICES — compute, storage, network, cost (in scope) ─────────────────
    c('s46', 'services', 'Amazon EC2', 'Virtual servers (resizable compute)', { diff: 'easy', tag: 'Infrastructure', use: 'Run a self-hosted model or training job on your own instances.', example: 'Hosting an open-source LLM on a GPU instance you manage.' }),
    c('s47', 'services', 'AWS Lambda', 'Serverless functions — run code without managing servers', { diff: 'easy', tag: 'Infrastructure', use: 'Glue logic and lightweight inference calls, pay per use.', example: 'A function that calls Bedrock when a file lands in S3.' }),
    c('s48', 'services', 'Amazon S3', 'Object storage for any data', { diff: 'easy', tag: 'Infrastructure', use: 'The default home for datasets, documents and model artefacts.', example: 'Storing the documents a Knowledge Base will index for RAG.' }),
    c('s49', 'services', 'Amazon S3 Glacier', 'Low-cost archival (cold) storage', { diff: 'easy', tag: 'Infrastructure', use: 'Cheap long-term retention for data you rarely access.', example: 'Archiving old training datasets for compliance retention.' }),
    c('s50', 'services', 'Amazon ECS / Amazon EKS', 'Run containers (ECS) / managed Kubernetes (EKS)', { diff: 'easy', tag: 'Infrastructure', use: 'Deploy containerised model-serving or pipeline workloads.', example: 'Serving a custom model in containers behind an API.' }),
    c('s51', 'services', 'Amazon CloudFront', 'Content delivery network (CDN)', { diff: 'easy', tag: 'Infrastructure', use: 'Caches and serves content close to users for low latency.', example: 'Delivering a GenAI web app’s assets quickly worldwide.' }),
    c('s52', 'services', 'Amazon VPC', 'Isolated private network for your resources', { diff: 'easy', tag: 'Security', use: 'Keep inference and data traffic off the public internet.', example: 'Running a private endpoint reachable only inside your network.' }),
    c('s53', 'services', 'AWS Secrets Manager', 'Store and automatically rotate secrets and credentials', { diff: 'easy', tag: 'Security', use: 'The answer for "store API keys / DB credentials securely".', example: 'Holding a third-party model API key and rotating it on a schedule.' }),
    c('s54', 'services', 'AWS Well-Architected Tool', 'Review workloads against AWS best practices', { diff: 'easy', tag: 'Security', use: 'Self-assess a workload, including the GenAI lens.', example: 'Checking a GenAI app against operational and security best practices.' }),
    c('s55', 'services', 'AWS Budgets / AWS Cost Explorer', 'Set cost budgets & alerts / visualise and analyse spend', { diff: 'easy', tag: 'Cost', use: 'Track and forecast AI project spend, alert on overruns.', example: 'Alerting when monthly Bedrock token spend exceeds a budget.' }),

    // ───────────────── SERVICES — data, database, analytics (in scope) ─────────────────
    c('s56', 'services', 'Amazon Aurora / Amazon RDS', 'Managed relational databases (PostgreSQL can store vectors)', { diff: 'easy', tag: 'Data', use: 'Relational data; pgvector makes them vector stores for RAG.', example: 'Aurora PostgreSQL holding embeddings for semantic search.' }),
    c('s57', 'services', 'Amazon DynamoDB', 'Managed NoSQL key-value & document database', { diff: 'easy', tag: 'Data', use: 'Fast, scalable storage for app and session state.', example: 'Storing a chatbot’s per-user conversation state.' }),
    c('s58', 'services', 'Amazon DocumentDB', 'Managed document database (MongoDB-compatible)', { diff: 'easy', tag: 'Data', use: 'JSON-style document storage at scale.', example: 'Holding semi-structured product data for an app.' }),
    c('s59', 'services', 'Amazon ElastiCache', 'In-memory cache (Redis / Memcached)', { diff: 'easy', tag: 'Data', use: 'Sub-millisecond caching to cut latency and cost.', example: 'Caching frequent responses in front of a model API.' }),
    c('s60', 'services', 'Amazon Neptune', 'Managed graph database (supports vector search)', { diff: 'easy', tag: 'Data', use: 'Relationship-heavy data; can also store embeddings.', example: 'A knowledge graph backing a RAG application.' }),
    c('s61', 'services', 'Amazon OpenSearch Service', 'Search and analytics — popular vector store for RAG', { diff: 'easy', tag: 'Data', use: 'The common managed vector database for embeddings.', example: 'Indexing document vectors so a RAG bot can retrieve them.' }),
    c('s62', 'services', 'AWS Glue', 'Serverless ETL and data catalog', { diff: 'easy', tag: 'Data', use: 'Extract, transform and load data to prepare it for ML.', example: 'Cleaning and joining raw data before training a model.' }),
    c('s63', 'services', 'AWS Glue DataBrew', 'Visual, no-code data preparation', { diff: 'intermediate', tag: 'Data', use: 'Clean and normalise data through a point-and-click UI.', example: 'A non-coder profiling and cleaning a dataset with recipes.' }),
    c('s64', 'services', 'AWS Lake Formation', 'Build and secure data lakes with central permissions', { diff: 'intermediate', tag: 'Data', use: 'Fine-grained access control over a data lake.', example: 'Granting row- and column-level access to a shared dataset.' }),
    c('s65', 'services', 'AWS Data Exchange', 'Find and subscribe to third-party datasets', { diff: 'intermediate', tag: 'Data', use: 'Source external data to enrich models and analytics.', example: 'Subscribing to a market-data feed to enrich a forecast.' }),
    c('s66', 'services', 'Amazon EMR', 'Big-data processing (Spark, Hadoop)', { diff: 'intermediate', tag: 'Data', use: 'Process very large datasets for analytics or feature prep.', example: 'Running Spark jobs to build features over terabytes of logs.' }),
    c('s67', 'services', 'Amazon Redshift', 'Cloud data warehouse', { diff: 'easy', tag: 'Data', use: 'Analytics over structured data at scale.', example: 'Querying business data to compute model performance metrics.' }),

    // ───────────────── SERVICES — tested extras (beyond current guide) ─────────────────
    c('s68', 'services', 'SageMaker Data Wrangler', 'Visual data preparation and feature engineering', { diff: 'advanced', tag: 'Beyond guide', use: 'Import, clean and transform data inside SageMaker.', example: 'Building model features through a visual flow.' }),
    c('s69', 'services', 'SageMaker Feature Store', 'Central store to save, share and serve ML features', { diff: 'advanced', tag: 'Beyond guide', use: 'Reuse consistent features across training and inference.', example: 'Sharing the same engineered features across several models.' }),
    c('s70', 'services', 'SageMaker Canvas', 'No-code ML — build models and predictions visually', { diff: 'advanced', tag: 'Beyond guide', use: 'Lets business analysts build models without writing code.', example: 'An analyst predicting churn from a spreadsheet, no code.' }),
    c('s71', 'services', 'SageMaker Ground Truth', 'Human and automated data labeling', { diff: 'advanced', tag: 'Beyond guide', use: 'Create high-quality labeled datasets for supervised learning.', example: 'Labelling thousands of images to train a vision model.' }),
    c('s72', 'services', 'SageMaker Pipelines', 'Build and automate ML workflows (CI/CD for ML)', { diff: 'advanced', tag: 'Beyond guide', use: 'Orchestrate repeatable train/eval/deploy steps — MLOps.', example: 'Auto-retraining and redeploying when new data arrives.' }),
    c('s73', 'services', 'Amazon Forecast', 'Time-series forecasting', { diff: 'advanced', tag: 'Beyond guide', use: 'Predict future values from historical time-series data.', example: 'Forecasting product demand for the next quarter.' }),
    c('s74', 'services', 'Amazon Fraud Detector', 'Detect potentially fraudulent online activity', { diff: 'advanced', tag: 'Beyond guide', use: 'Managed ML to score the risk of fraud in real time.', example: 'Flagging suspicious new-account sign-ups or payments.' }),
    c('s75', 'services', 'AWS Trainium / AWS Inferentia', 'Custom chips — Trainium accelerates training, Inferentia accelerates inference', { diff: 'advanced', tag: 'Beyond guide', use: 'Purpose-built accelerators that lower the cost of deep learning.', example: 'Cutting the cost of training or serving a large model.' }),

    // ───────────────── CORE CONCEPTS (new) ─────────────────
    // Domain 1 — fundamentals of AI & ML
    c('k27', 'concepts', 'Types of data in AI', 'Structured vs unstructured; tabular, time-series, image, text; labeled vs unlabeled', { diff: 'intermediate', use: 'Know which data type a scenario describes to pick the right approach.', example: 'Time-series sales for forecasting; unstructured text for an LLM.' }),
    c('k28', 'concepts', 'Labeled vs unlabeled data', 'Labeled has known answers (supervised); unlabeled has none (unsupervised)', { diff: 'easy', use: 'Labels present → supervised; absent → unsupervised.', example: 'Emails marked spam/not (labeled) vs raw logs to cluster (unlabeled).' }),
    c('k29', 'concepts', 'Neural networks', 'Layered models loosely inspired by the brain; the basis of deep learning', { diff: 'easy', use: 'Many connected layers learn complex patterns from data.', example: 'The network behind image and speech recognition.' }),
    c('k30', 'concepts', 'Computer vision', 'AI that interprets images and video', { diff: 'easy', use: 'Detect, classify or locate objects and faces in media.', example: 'Spotting defects on a production line from camera frames.' }),
    c('k31', 'concepts', 'AI/ML development lifecycle', 'Data collection → preparation → training → evaluation → deployment → monitoring', { diff: 'intermediate', use: 'The repeatable stages of building and running an ML model.', example: 'Monitoring a deployed model and retraining when it drifts.' }),
    c('k32', 'concepts', 'What is MLOps?', 'Practices for repeatable, scalable ML: deployment, monitoring, retraining, managing tech debt', { diff: 'intermediate', use: 'Operationalises ML so models stay healthy in production.', example: 'Automated pipelines that retrain and redeploy on a schedule.' }),
    c('k33', 'concepts', 'Using a model in production', 'Managed API service (e.g. Bedrock) vs self-hosted API (your own servers)', { diff: 'intermediate', use: 'Trade convenience (managed) against control (self-hosted).', example: 'Calling Bedrock’s API instead of hosting a model on EC2.' }),
    c('k34', 'concepts', 'Sources of foundation models', 'Open-source pre-trained models vs models you train/customise yourself', { diff: 'intermediate', use: 'Start from a pre-trained FM rather than building from scratch.', example: 'Using a pre-trained FM in Bedrock instead of training one.' }),
    c('k35', 'concepts', 'When AI/ML is NOT appropriate', 'When a guaranteed exact outcome is needed, or cost outweighs benefit', { diff: 'intermediate', use: 'Prefer deterministic rules when predictions aren’t acceptable.', example: 'Tax calculations need exact rules, not a probabilistic model.' }),

    // Domain 2 — fundamentals of GenAI
    c('k36', 'concepts', 'Tokens', 'The chunks of text models read and generate; pricing is usually per token', { diff: 'intermediate', use: 'Token counts drive both cost and latency of inference.', example: 'A long prompt and answer cost more because they use more tokens.' }),
    c('k37', 'concepts', 'Embeddings & vectors', 'Numeric representations of meaning; similar items sit close in vector space', { diff: 'intermediate', use: 'Embeddings power semantic search and RAG retrieval.', example: 'Finding documents whose meaning matches a question.' }),
    c('k38', 'concepts', 'Chunking', 'Splitting long documents into smaller pieces before embedding', { diff: 'easy', use: 'Right-sized chunks improve RAG retrieval quality.', example: 'Breaking a 50-page manual into sections to index for RAG.' }),
    c('k39', 'concepts', 'Transformers', 'The neural architecture (attention) behind modern LLMs', { diff: 'easy', use: 'The model design that made large language models possible.', example: 'The architecture underlying today’s chat models.' }),
    c('k40', 'concepts', 'Diffusion models', 'Generative models that create images from noise', { diff: 'easy', use: 'The technique behind text-to-image generation.', example: 'Producing an image from a written description.' }),
    c('k41', 'concepts', 'Multi-modal models', 'Models that handle more than one input/output type (text, image, audio)', { diff: 'easy', use: 'One model reasons over text and images together.', example: 'Describing what is happening in an uploaded photo.' }),
    c('k42', 'concepts', 'FM lifecycle', 'Data selection → pre-training → fine-tuning → evaluation → deployment → feedback', { diff: 'intermediate', use: 'The end-to-end stages of creating and improving an FM.', example: 'Collecting feedback after launch to guide the next tuning round.' }),
    c('k43', 'concepts', 'Context engineering', 'Designing what information goes into the model’s context window', { diff: 'intermediate', use: 'Supply the right context (retrieved data, instructions, history).', example: 'Injecting the relevant policy section so an answer is grounded.' }),
    c('k44', 'concepts', 'Agentic AI patterns', 'Single-agent vs multi-agent systems with planning and tool use', { diff: 'advanced', use: 'Break complex tasks across agents that coordinate.', example: 'A planner agent delegating subtasks to specialist agents.' }),
    c('k45', 'concepts', 'MCP — what it does', 'Model Context Protocol: a standard way to connect agents to external tools and data', { diff: 'intermediate', use: 'Lets agents call tools and data sources through one open protocol.', example: 'An agent querying a database and ticketing system via MCP.' }),
    c('k46', 'concepts', 'Agent memory & tool use', 'Memory keeps context across steps; tools let agents act (call APIs, run code)', { diff: 'intermediate', use: 'The two capabilities that make an agent more than a chatbot.', example: 'An agent remembering a goal while calling APIs to complete it.' }),
    c('k47', 'concepts', 'GenAI advantages', 'Adaptable, responsive, conversational, can generate new content fast', { diff: 'easy', use: 'Why teams reach for GenAI over rigid rules.', example: 'Drafting tailored replies instantly instead of templates.' }),
    c('k48', 'concepts', 'GenAI disadvantages', 'Hallucinations, inaccuracy, nondeterminism, limited interpretability', { diff: 'intermediate', use: 'The risks to plan for when adopting GenAI.', example: 'A model confidently inventing a fact (hallucination).' }),
    c('k49', 'concepts', 'Choosing a GenAI model', 'Weigh cost, latency, modality, size, capability, compliance and constraints', { diff: 'advanced', use: 'No single "best" model — match it to the requirements.', example: 'Picking a small fast model for chat, a larger one for analysis.' }),
    c('k50', 'concepts', 'GenAI business value metrics', 'ROI, conversion rate, ARPU, customer lifetime value, efficiency, cross-domain performance', { diff: 'intermediate', use: 'Tie a GenAI app back to measurable business outcomes.', example: 'Reporting conversion lift and ROI from an AI assistant.' }),
    c('k51', 'concepts', 'Token-based pricing & cost', 'You pay per input/output token; provisioned throughput buys guaranteed capacity', { diff: 'advanced', use: 'Control cost via prompt size, model choice and throughput mode.', example: 'Choosing on-demand for spiky traffic, provisioned for steady load.' }),

    // Domain 3 — applications of foundation models
    c('k52', 'concepts', 'FM selection criteria', 'Cost, modality, latency, multi-lingual, model size, input/output length, prompt caching', { diff: 'advanced', use: 'The concrete factors to compare FMs against your use case.', example: 'Needing long context and multilingual support narrows the choices.' }),
    c('k53', 'concepts', 'Inference parameters', 'Temperature (randomness), top-p / top-k (sampling), max length', { diff: 'intermediate', use: 'Tune output style and length without changing the model.', example: 'Low temperature and capped length for terse factual replies.' }),
    c('k54', 'concepts', 'Prompt caching', 'Reuse a cached prompt prefix to cut latency and cost on repeated calls', { diff: 'intermediate', use: 'Avoid reprocessing the same large context every request.', example: 'Caching a long system prompt shared across many requests.' }),
    c('k55', 'concepts', 'Model distillation', 'Train a small student model to mimic a large teacher — cheaper, faster', { diff: 'advanced', use: 'A customisation option to lower cost at near-teacher quality.', example: 'Distilling a big model for high-volume, latency-sensitive calls.' }),
    c('k56', 'concepts', 'In-context learning', 'The model learns from examples in the prompt — no training', { diff: 'easy', use: 'Few-shot examples steer behaviour without fine-tuning.', example: 'Showing two formatted samples so output matches the format.' }),
    c('k57', 'concepts', 'Continued pre-training', 'Further pre-train an FM on large domain data to absorb its language', { diff: 'intermediate', use: 'Used when prompting and RAG aren’t enough for a domain.', example: 'Pre-training further on medical text for a clinical assistant.' }),
    c('k58', 'concepts', 'Fine-tuning methods', 'Instruction tuning, domain adaptation, transfer learning (uses labeled data)', { diff: 'intermediate', use: 'Adjust the model’s weights for a task or domain.', example: 'Instruction-tuning a model to follow your support tone.' }),
    c('k59', 'concepts', 'Preparing data to fine-tune', 'Curation, governance, sizing, labeling, representativeness; RLHF for alignment', { diff: 'intermediate', use: 'Data quality and balance decide fine-tuning success.', example: 'Curating balanced, well-labelled examples before tuning.' }),
    c('k60', 'concepts', 'Evaluating an FM', 'Human-in-the-loop review, benchmark datasets, Bedrock Model Evaluation', { diff: 'intermediate', use: 'Methods to judge whether a model is good enough.', example: 'Running your own prompts through Bedrock Model Evaluation.' }),
    c('k61', 'concepts', 'LLM-as-a-judge', 'Use a strong model to score another model’s outputs', { diff: 'intermediate', use: 'Scales evaluation of generated text beyond human review.', example: 'A judge model rating answer quality across hundreds of cases.' }),
    c('k62', 'concepts', 'AI agents', 'Systems that plan multi-step tasks and call tools to act, not just answer', { diff: 'intermediate', use: 'Automate workflows that need decisions and actions.', example: 'An agent that researches, drafts and files a report end to end.' }),
    c('k63', 'concepts', 'Prompt engineering best practices', 'Be specific and concise, give context, add examples, set guardrails, experiment', { diff: 'intermediate', use: 'The cheapest way to lift output quality.', example: 'Adding clear instructions and an example to fix vague answers.' }),

    // Domain 4 — responsible AI
    c('k64', 'concepts', 'Legal risks of GenAI', 'IP infringement, biased outputs, loss of customer trust, end-user harm, hallucinations', { diff: 'advanced', use: 'The legal and trust exposures to govern against.', example: 'Generated text that copies protected work, creating IP risk.' }),
    c('k65', 'concepts', 'Dataset characteristics', 'Inclusive, diverse, balanced and curated data reduces bias', { diff: 'intermediate', use: 'Good datasets are the first defence against unfair models.', example: 'Balancing under-represented groups in training data.' }),
    c('k66', 'concepts', 'Sustainability in model choice', 'Prefer smaller/efficient models and reuse to cut energy and cost', { diff: 'intermediate', use: 'A responsible-AI factor: environmental impact of compute.', example: 'Choosing a smaller model when it meets the requirement.' }),
    c('k67', 'concepts', 'Effects of bias & variance', 'High bias → underfitting; high variance → overfitting; both can harm groups', { diff: 'intermediate', use: 'Diagnose model error and its fairness impact.', example: 'An overfit model that fails for an under-represented group.' }),
    c('k68', 'concepts', 'Bias detection tools', 'SageMaker Clarify, SageMaker Model Monitor, Amazon A2I, human audits, subgroup analysis', { diff: 'intermediate', use: 'How you find and watch bias and drift.', example: 'Using Clarify to surface bias before deploying a model.' }),
    c('k69', 'concepts', 'Human-centred design for XAI', 'Build user feedback loops and clear AI decision transparency', { diff: 'intermediate', use: 'Design explainable AI around the people who use it.', example: 'Showing why a recommendation was made and letting users correct it.' }),
    c('k70', 'concepts', 'Interpretability vs performance', 'More accurate models are often less interpretable — a deliberate tradeoff', { diff: 'advanced', use: 'Balance accuracy against the need to explain decisions.', example: 'Choosing a simpler, explainable model for a regulated decision.' }),

    // Domain 5 — security, compliance & governance
    c('k71', 'concepts', 'Securing AI systems', 'IAM, encryption, Macie, PrivateLink, Bedrock Guardrails, AgentCore Identity', { diff: 'intermediate', use: 'Layered controls for data, access and model output.', example: 'Locking down who can call a model and what it can return.' }),
    c('k72', 'concepts', 'Encryption at rest & in transit', 'KMS-managed keys protect stored data; TLS protects data in motion', { diff: 'intermediate', use: 'Protect data wherever it sits or moves.', example: 'Encrypting training data in S3 and the API calls to a model.' }),
    c('k73', 'concepts', 'Source citation & data lineage', 'Track data origins and cite sources; document with SageMaker Model Cards', { diff: 'intermediate', use: 'Prove where data and answers came from for trust and audits.', example: 'A RAG answer that links the document it was drawn from.' }),
    c('k74', 'concepts', 'Secure data engineering', 'Assess data quality, use privacy-enhancing tech, control access, protect integrity', { diff: 'intermediate', use: 'Build pipelines that keep data safe and trustworthy.', example: 'Masking PII and restricting who can read a training set.' }),
    c('k75', 'concepts', 'Prompt injection', 'Malicious input that overrides instructions; mitigate with guardrails & validation', { diff: 'intermediate', use: 'A top LLM threat — untrusted input hijacking the prompt.', example: 'A user message that tries to make a bot ignore its rules.' }),
    c('k76', 'concepts', 'Data leakage & output filtering', 'Stop sensitive data leaving via outputs; validate and filter responses', { diff: 'intermediate', use: 'Prevent models from revealing private or unsafe content.', example: 'Blocking a model from echoing secrets it saw in context.' }),
    c('k77', 'concepts', 'Toxicity & content filtering', 'Detect and block harmful, hateful or unsafe content (Bedrock Guardrails)', { diff: 'easy', use: 'Keep model output safe for users.', example: 'Filtering out hateful text from a public chatbot.' }),
    c('k78', 'concepts', 'Audit trail & logging', 'Log AI interactions and API calls (CloudTrail) for accountability', { diff: 'intermediate', use: 'Record who did what for security and compliance.', example: 'Logging every model invocation for a later audit.' }),
    c('k79', 'concepts', 'Data governance strategies', 'Data lifecycle, residency, retention, logging, monitoring and observation', { diff: 'intermediate', use: 'Policies for how data is kept, located and managed.', example: 'Keeping EU customer data in-region to meet residency rules.' }),
    c('k80', 'concepts', 'Governance frameworks', 'Policies, review cadence, training and the Generative AI Security Scoping Matrix', { diff: 'advanced', use: 'Structured processes to govern AI responsibly.', example: 'Using the scoping matrix to classify a GenAI app’s risk.' }),

    // ───────────────── QUESTION PATTERNS (new) ─────────────────
    c('p19', 'patterns', 'Need an AI coding assistant in the IDE?', 'Amazon Q Developer', { diff: 'intermediate', use: 'Trigger words: code generation, in-IDE help, developer.', example: 'Generating and explaining code while you write it.' }),
    c('p20', 'patterns', 'Need a GenAI assistant over your company data?', 'Amazon Q Business', { diff: 'intermediate', use: 'Trigger words: enterprise data, cited answers, permissions-aware.', example: 'Employees querying internal docs in plain English.' }),
    c('p21', 'patterns', 'Need to run autonomous tool-using agents at scale?', 'Bedrock AgentCore', { diff: 'advanced', use: 'Trigger words: deploy agents, memory, identity, securely.', example: 'Hosting a production support agent that calls internal APIs.' }),
    c('p22', 'patterns', 'Need a standard way to connect agents to tools/data?', 'MCP (Model Context Protocol)', { diff: 'intermediate', use: 'Trigger words: connect agents, external systems, standard protocol.', example: 'An agent reaching a database and ticketing system uniformly.' }),
    c('p23', 'patterns', 'Need a smaller, cheaper model with similar quality?', 'Model distillation', { diff: 'advanced', use: 'Trigger words: reduce cost/latency, keep quality, smaller model.', example: 'Serving high volumes cheaply after distilling a big model.' }),
    c('p24', 'patterns', 'Need to cut latency/cost on a repeated long prompt?', 'Prompt caching', { diff: 'advanced', use: 'Trigger words: repeated context, reduce latency and cost.', example: 'Caching a shared system prompt across many calls.' }),
    c('p25', 'patterns', 'Need guaranteed capacity for production GenAI?', 'Provisioned throughput', { diff: 'advanced', use: 'Trigger words: steady high load, guaranteed throughput.', example: 'Reserving capacity for a constant production workload.' }),
    c('p26', 'patterns', 'Need to store & rotate API keys or credentials?', 'AWS Secrets Manager', { diff: 'intermediate', use: 'Trigger words: secrets, credentials, rotation.', example: 'Holding a model provider API key securely.' }),
    c('p27', 'patterns', 'Need to track or alert on AI project spend?', 'AWS Budgets / Cost Explorer', { diff: 'intermediate', use: 'Trigger words: cost, budget, alert, analyse spend.', example: 'Alerting when token spend passes a threshold.' }),
    c('p28', 'patterns', 'Need to review a workload against best practices?', 'AWS Well-Architected Tool', { diff: 'intermediate', use: 'Trigger words: best practices, review, GenAI lens.', example: 'Assessing a GenAI workload before launch.' }),
    c('p29', 'patterns', 'Need to build and secure a data lake?', 'AWS Lake Formation', { diff: 'intermediate', use: 'Trigger words: data lake, fine-grained permissions.', example: 'Granting column-level access to a shared dataset.' }),
    c('p30', 'patterns', 'Need no-code data preparation?', 'AWS Glue DataBrew', { diff: 'intermediate', use: 'Trigger words: clean data, visual, no code.', example: 'An analyst cleaning a dataset without scripting.' }),
    c('p31', 'patterns', 'Need to forecast future time-series values?', 'Amazon Forecast', { diff: 'advanced', use: 'Trigger words: forecast, demand, time series.', example: 'Predicting next month’s inventory needs.' }),
    c('p32', 'patterns', 'Need to detect online fraud?', 'Amazon Fraud Detector', { diff: 'advanced', use: 'Trigger words: fraud, risk score, transactions.', example: 'Scoring new sign-ups for fraud risk.' }),
    c('p33', 'patterns', 'Need to label training data?', 'SageMaker Ground Truth', { diff: 'advanced', use: 'Trigger words: label data, human annotation.', example: 'Labelling images to train a classifier.' }),
    c('p34', 'patterns', 'Need no-code ML for a business analyst?', 'SageMaker Canvas', { diff: 'advanced', use: 'Trigger words: no code, analyst, predictions.', example: 'Predicting churn from a spreadsheet without code.' }),
    c('p35', 'patterns', 'Need to evaluate which FM fits your task?', 'Bedrock Model Evaluation', { diff: 'intermediate', use: 'Trigger words: compare models, evaluate, metrics.', example: 'Scoring two models on your own prompts.' }),
    c('p36', 'patterns', 'Need to scope a GenAI app’s security & risk?', 'Generative AI Security Scoping Matrix', { diff: 'advanced', use: 'Trigger words: governance, scope, security framework.', example: 'Classifying a GenAI app to decide its controls.' }),
  ];

  // Every card carries a difficulty. New cards set it explicitly; existing
  // cards default by category, with a few overrides for clearly easy/advanced ones.
  const DIFF_BY_CAT = { acronyms: 'easy', services: 'easy', concepts: 'intermediate', patterns: 'intermediate' };
  const DIFF_OVERRIDE = {
    k1: 'easy', k3: 'easy', k4: 'easy', k5: 'easy', k7: 'easy', k8: 'easy', k9: 'easy', k16: 'easy', k25: 'easy',
    k19: 'advanced', k23: 'advanced', k26: 'advanced',
  };
  for (const card of cards) card.diff = card.diff || DIFF_OVERRIDE[card.id] || DIFF_BY_CAT[card.cat] || 'intermediate';

  return { categories, cards };
})();
