/* AIF-C01 quiz bank — curated multiple-choice questions, grouped by category.
   Each question: { q, options: [4], correct: <exact option text>, explain } */

export const quiz = (function () {
  const Q = (q, options, correct, explain) => ({ q, options, correct, explain });

  const categories = [
    {
      id: 'services', name: 'AWS Services', hue: 188,
      blurb: 'Match the service to the job.',
      questions: [
        Q('Which service converts speech to text?',
          ['Amazon Transcribe', 'Amazon Polly', 'Amazon Translate', 'Amazon Comprehend'],
          'Amazon Transcribe', 'Transcribe = speech → text. Polly does the reverse.'),
        Q('Which service turns text into lifelike spoken audio?',
          ['Amazon Polly', 'Amazon Transcribe', 'Amazon Lex', 'Amazon Kendra'],
          'Amazon Polly', 'Polly = text → speech (voice).'),
        Q('You need to build a chatbot with voice and text. Which service?',
          ['Amazon Lex', 'Amazon Comprehend', 'Amazon Rekognition', 'Amazon Personalize'],
          'Amazon Lex', 'Lex powers conversational voice & text interfaces.'),
        Q('Which service detects objects and faces in images and video?',
          ['Amazon Rekognition', 'Amazon Textract', 'Amazon Comprehend', 'Amazon Kendra'],
          'Amazon Rekognition', 'Rekognition is the computer-vision service.'),
        Q('Extract data from scanned invoices and forms?',
          ['Amazon Textract', 'Amazon Rekognition', 'Amazon Comprehend', 'Amazon Translate'],
          'Amazon Textract', 'Textract does document OCR + structured extraction.'),
        Q('Detect sentiment, entities and PII in text?',
          ['Amazon Comprehend', 'Amazon Lex', 'Amazon Polly', 'Amazon Kendra'],
          'Amazon Comprehend', 'Comprehend is the NLP service.'),
        Q('Intelligent natural-language search over enterprise documents?',
          ['Amazon Kendra', 'Amazon Comprehend', 'Amazon Textract', 'Amazon Macie'],
          'Amazon Kendra', 'Kendra = ML-powered enterprise search.'),
        Q('Generate product recommendations like Amazon.com?',
          ['Amazon Personalize', 'Amazon Forecast', 'Amazon Rekognition', 'Amazon Q'],
          'Amazon Personalize', 'Personalize builds recommendation systems.'),
        Q('Central service to access foundation models via an API?',
          ['Amazon Bedrock', 'Amazon SageMaker AI', 'Amazon Comprehend', 'Amazon Q'],
          'Amazon Bedrock', 'Bedrock is the managed FM access service.'),
        Q('Add a human review step for low-confidence ML predictions?',
          ['Amazon A2I', 'SageMaker Clarify', 'Bedrock Guardrails', 'Amazon Macie'],
          'Amazon A2I', 'A2I = Augmented AI, human-in-the-loop review.'),
        Q('Block toxic or harmful foundation-model output?',
          ['Bedrock Guardrails', 'Amazon Macie', 'SageMaker Clarify', 'AWS IAM'],
          'Bedrock Guardrails', 'Guardrails filter unsafe content.'),
        Q('Detect bias and explain a model\u2019s predictions?',
          ['SageMaker Clarify', 'SageMaker Model Monitor', 'SageMaker Model Cards', 'Amazon Comprehend'],
          'SageMaker Clarify', 'Clarify = bias detection + explainability.'),
        Q('Document a model\u2019s purpose, data and lineage for transparency?',
          ['SageMaker Model Cards', 'SageMaker Model Monitor', 'SageMaker Clarify', 'AWS Artifact'],
          'SageMaker Model Cards', 'Model Cards capture model documentation.'),
        Q('Detect data or quality drift in a deployed model?',
          ['SageMaker Model Monitor', 'SageMaker Clarify', 'Amazon CloudWatch', 'AWS Config'],
          'SageMaker Model Monitor', 'Model Monitor watches production models for drift.'),
        Q('Audit which API calls were made, when and by whom?',
          ['AWS CloudTrail', 'Amazon CloudWatch', 'AWS Config', 'Amazon Inspector'],
          'AWS CloudTrail', 'CloudTrail logs API activity for auditing.'),
        Q('Discover sensitive PII stored in Amazon S3?',
          ['Amazon Macie', 'Amazon Inspector', 'Amazon GuardDuty', 'Amazon Comprehend'],
          'Amazon Macie', 'Macie finds and protects sensitive data in S3.'),
      ],
    },

    {
      id: 'acronyms', name: 'Acronyms', hue: 286,
      blurb: 'Expand the abbreviation.',
      questions: [
        Q('RAG stands for…',
          ['Retrieval Augmented Generation', 'Rapid AI Generation', 'Ranked Answer Grouping', 'Recursive Agent Graph'],
          'Retrieval Augmented Generation', 'RAG retrieves external data to ground an FM.'),
        Q('LLM stands for…',
          ['Large Language Model', 'Layered Learning Machine', 'Logical Language Module', 'Long Latency Model'],
          'Large Language Model', 'LLMs generate and understand text.'),
        Q('FM stands for…',
          ['Foundation Model', 'Functional Model', 'Federated Model', 'Fine-tuned Model'],
          'Foundation Model', 'A large pre-trained model adapted to many tasks.'),
        Q('RLHF stands for…',
          ['Reinforcement Learning from Human Feedback', 'Recurrent Learning of Human Factors', 'Rule-based Learning & Human Filtering', 'Random Loss Heuristic Function'],
          'Reinforcement Learning from Human Feedback', 'RLHF aligns models to human preferences.'),
        Q('NLP stands for…',
          ['Natural Language Processing', 'Neural Logic Programming', 'Network Layer Protocol', 'Native Language Parser'],
          'Natural Language Processing', 'NLP lets machines work with human language.'),
        Q('MCP stands for…',
          ['Model Context Protocol', 'Managed Compute Platform', 'Multi-Cloud Pipeline', 'Model Compression Process'],
          'Model Context Protocol', 'MCP connects agents to external systems.'),
        Q('MLOps refers to…',
          ['Machine Learning Operations', 'Model Lifecycle Optimization', 'Multi-Layer Operations', 'Managed Learning Ops'],
          'Machine Learning Operations', 'Practices to deploy & maintain ML in production.'),
        Q('BLEU is a metric for…',
          ['Translation quality', 'Summarization quality', 'Image quality', 'Classification accuracy'],
          'Translation quality', 'BLEU scores machine translation.'),
        Q('ROUGE is mainly used to evaluate…',
          ['Text summarization', 'Translation', 'Clustering', 'Regression'],
          'Text summarization', 'ROUGE compares a summary to a reference.'),
        Q('The F1 score is…',
          ['The harmonic mean of precision and recall', 'Accuracy divided by recall', 'The area under the ROC curve', 'Mean squared error'],
          'The harmonic mean of precision and recall', 'F1 balances precision and recall.'),
        Q('BERTScore measures…',
          ['Semantic similarity of generated text', 'Number of tokens used', 'Training loss', 'Inference latency'],
          'Semantic similarity of generated text', 'It judges meaning, not exact words.'),
        Q('A2I provides…',
          ['Human-in-the-loop review of predictions', 'Auto-scaling inference', 'API gateway integration', 'Anomaly insights'],
          'Human-in-the-loop review of predictions', 'A2I = Amazon Augmented AI.'),
        Q('AWS KMS manages…',
          ['Encryption keys', 'Access roles', 'Model versions', 'Network routes'],
          'Encryption keys', 'KMS = Key Management Service.'),
        Q('AWS IAM controls…',
          ['Access to AWS resources', 'Model accuracy', 'Inference autoscaling', 'Data ingestion rate'],
          'Access to AWS resources', 'IAM = Identity and Access Management.'),
      ],
    },

    {
      id: 'concepts', name: 'Core Concepts', hue: 150,
      blurb: 'ML & GenAI fundamentals.',
      questions: [
        Q('Labeled training data is used in which learning type?',
          ['Supervised learning', 'Unsupervised learning', 'Reinforcement learning', 'Self-supervised learning'],
          'Supervised learning', 'Labels → supervised (classification, regression).'),
        Q('Grouping unlabeled data into segments is…',
          ['Clustering (unsupervised)', 'Classification', 'Regression', 'Reinforcement learning'],
          'Clustering (unsupervised)', 'No labels + grouping = unsupervised clustering.'),
        Q('Learning from rewards and penalties is…',
          ['Reinforcement learning', 'Supervised learning', 'Unsupervised learning', 'Transfer learning'],
          'Reinforcement learning', 'Reward signal → reinforcement (also RLHF).'),
        Q('Predicting a continuous number (e.g. a price) is…',
          ['Regression', 'Classification', 'Clustering', 'Ranking'],
          'Regression', 'Regression predicts a quantity; classification predicts a label.'),
        Q('A model that is too simple and underfits has…',
          ['High bias', 'High variance', 'Low bias', 'No error'],
          'High bias', 'High bias = underfitting.'),
        Q('A model that memorizes the training data has…',
          ['High variance (overfitting)', 'High bias', 'Underfitting', 'Low variance'],
          'High variance (overfitting)', 'High variance = overfitting.'),
        Q('Raising an LLM\u2019s temperature makes output…',
          ['More random and creative', 'More deterministic', 'Shorter', 'More factual'],
          'More random and creative', 'Higher temperature = more randomness.'),
        Q('The cheapest, least-effort way to customize an FM is…',
          ['Prompt engineering', 'Fine-tuning', 'Continued pre-training', 'Pre-training from scratch'],
          'Prompt engineering', 'Prompt engineering needs no training.'),
        Q('Which is the MOST expensive way to customize an FM?',
          ['Pre-training from scratch', 'Prompt engineering', 'RAG', 'Fine-tuning'],
          'Pre-training from scratch', 'The top of the cost ladder.'),
        Q('Which approach grounds an FM in your own documents?',
          ['RAG', 'Raising temperature', 'Fine-tuning the tokenizer', 'Quantization'],
          'RAG', 'RAG retrieves your data to reduce hallucination.'),
        Q('Which metric set evaluates generated text (not classifiers)?',
          ['ROUGE, BLEU, BERTScore', 'Accuracy, precision, recall', 'RMSE and MAE', 'Silhouette score'],
          'ROUGE, BLEU, BERTScore', 'These judge generated language.'),
        Q('Few-shot prompting means…',
          ['Giving a few examples inside the prompt', 'Training on a few samples', 'Using a small model', 'Running a few epochs'],
          'Giving a few examples inside the prompt', 'Examples in-context, no training.'),
        Q('Chain-of-thought prompting encourages the model to…',
          ['Show step-by-step reasoning', 'Use fewer tokens', 'Avoid examples', 'Lower its temperature'],
          'Show step-by-step reasoning', 'CoT elicits intermediate reasoning steps.'),
        Q('GenAI sits inside which nesting?',
          ['AI ⊃ ML ⊃ Deep Learning ⊃ GenAI', 'ML ⊃ AI ⊃ GenAI', 'GenAI ⊃ AI ⊃ ML', 'AI ⊃ GenAI ⊃ ML'],
          'AI ⊃ ML ⊃ Deep Learning ⊃ GenAI', 'GenAI is a subset of deep learning.'),
      ],
    },

    {
      id: 'patterns', name: 'Scenarios & Responsible AI', hue: 24,
      blurb: 'Pick the right answer for the situation.',
      questions: [
        Q('A bank needs an explainable, auditable model for loan approvals. Choose…',
          ['Traditional ML', 'A large foundation model', 'A RAG chatbot', 'A diffusion model'],
          'Traditional ML', 'Regulatory / explainability needs favor traditional ML.'),
        Q('You must stop a chatbot from producing hateful content. Use…',
          ['Bedrock Guardrails', 'SageMaker Clarify', 'Amazon Macie', 'AWS IAM'],
          'Bedrock Guardrails', 'Guardrails filter harmful output.'),
        Q('Support answers must cite your internal docs. Best approach…',
          ['RAG with Bedrock Knowledge Bases', 'Pre-train a new model', 'Raise the temperature', 'Use Amazon Polly'],
          'RAG with Bedrock Knowledge Bases', 'RAG grounds answers in your data.'),
        Q('Under the shared responsibility model, who secures the data you put in S3?',
          ['The customer', 'AWS', 'AWS and the customer equally', 'The AWS Region'],
          'The customer', 'Customer secures in the cloud; AWS secures the cloud.'),
        Q('Which Well-Architected concern covers fairness and bias mitigation?',
          ['Responsible AI', 'Operational excellence', 'Cost optimization', 'Performance efficiency'],
          'Responsible AI', 'Fairness, safety and veracity are Responsible-AI pillars.'),
        Q('You want the least-effort tweak to an FM\u2019s tone. Start with…',
          ['Prompt engineering', 'Continued pre-training', 'Training a new model', 'RLHF'],
          'Prompt engineering', 'Always try prompting before training.'),
        Q('Where do you store vector embeddings for RAG?',
          ['Amazon OpenSearch Service', 'Amazon DynamoDB', 'Amazon S3 Glacier', 'Amazon CloudFront'],
          'Amazon OpenSearch Service', 'Vector DBs: OpenSearch, Aurora, Neptune, RDS for PostgreSQL.'),
        Q('Unlabeled customer data, and you want to find natural groups. Use…',
          ['Unsupervised clustering', 'Supervised classification', 'Reinforcement learning', 'Regression'],
          'Unsupervised clustering', 'No labels + grouping = unsupervised.'),
        Q('Translate a live chat between English and Japanese. Use…',
          ['Amazon Translate', 'Amazon Transcribe', 'Amazon Comprehend', 'Amazon Polly'],
          'Amazon Translate', 'Translate handles language translation.'),
        Q('Add captions to recorded webinars. Use…',
          ['Amazon Transcribe', 'Amazon Polly', 'Amazon Lex', 'Amazon Kendra'],
          'Amazon Transcribe', 'Transcribe converts the audio to text.'),
        Q('Classify product reviews as positive or negative. Use…',
          ['Amazon Comprehend', 'Amazon Rekognition', 'Amazon Personalize', 'Amazon Q'],
          'Amazon Comprehend', 'Comprehend does sentiment analysis.'),
        Q('Document model details for a transparency audit. Use…',
          ['SageMaker Model Cards', 'SageMaker Model Monitor', 'AWS CloudTrail', 'Bedrock Guardrails'],
          'SageMaker Model Cards', 'Model Cards record lineage and details.'),
      ],
    },
  ];

  return { categories };
})();
