/* AIF-C01 quiz bank — curated questions, grouped by category.
   Each question: { q, options, correct, explain, diff }
   - single-answer  → `correct` is the exact option text
   - multiple-response → `correct` is an array of exact option texts (graded all-or-nothing)
   - `diff` is 'easy' | 'intermediate' | 'advanced'; existing questions default by category */

export const quiz = (function () {
  const Q = (q, options, correct, explain, diff) => ({ q, options, correct, explain, diff });

  const categories = [
    {
      id: 'services', name: 'AWS Services', hue: 188,
      blurb: 'Match the service to the job.',
      questions: [
        Q('Which service converts speech to text?',
          ['Amazon Transcribe', 'Amazon Polly', 'Amazon Translate', 'Amazon Comprehend'],
          'Amazon Transcribe', 'Transcribe = speech → text. Polly does the reverse.'),
        Q('Which service turns text into lifelike spoken audio?',
          ['Amazon Polly', 'Amazon Transcribe', 'Amazon Lex', 'Amazon Kendra'],
          'Amazon Polly', 'Polly = text → speech (voice).'),
        Q('You need to build a chatbot with voice and text. Which service?',
          ['Amazon Lex', 'Amazon Comprehend', 'Amazon Rekognition', 'Amazon Personalize'],
          'Amazon Lex', 'Lex powers conversational voice & text interfaces.'),
        Q('Which service detects objects and faces in images and video?',
          ['Amazon Rekognition', 'Amazon Textract', 'Amazon Comprehend', 'Amazon Kendra'],
          'Amazon Rekognition', 'Rekognition is the computer-vision service.'),
        Q('Extract data from scanned invoices and forms?',
          ['Amazon Textract', 'Amazon Rekognition', 'Amazon Comprehend', 'Amazon Translate'],
          'Amazon Textract', 'Textract does document OCR + structured extraction.'),
        Q('Detect sentiment, entities and PII in text?',
          ['Amazon Comprehend', 'Amazon Lex', 'Amazon Polly', 'Amazon Kendra'],
          'Amazon Comprehend', 'Comprehend is the NLP service.'),
        Q('Intelligent natural-language search over enterprise documents?',
          ['Amazon Kendra', 'Amazon Comprehend', 'Amazon Textract', 'Amazon Macie'],
          'Amazon Kendra', 'Kendra = ML-powered enterprise search.'),
        Q('Generate product recommendations like Amazon.com?',
          ['Amazon Personalize', 'Amazon Forecast', 'Amazon Rekognition', 'Amazon Q'],
          'Amazon Personalize', 'Personalize builds recommendation systems.'),
        Q('Central service to access foundation models via an API?',
          ['Amazon Bedrock', 'Amazon SageMaker AI', 'Amazon Comprehend', 'Amazon Q'],
          'Amazon Bedrock', 'Bedrock is the managed FM access service.'),
        Q('Add a human review step for low-confidence ML predictions?',
          ['Amazon A2I', 'SageMaker Clarify', 'Bedrock Guardrails', 'Amazon Macie'],
          'Amazon A2I', 'A2I = Augmented AI, human-in-the-loop review.'),
        Q('Block toxic or harmful foundation-model output?',
          ['Bedrock Guardrails', 'Amazon Macie', 'SageMaker Clarify', 'AWS IAM'],
          'Bedrock Guardrails', 'Guardrails filter unsafe content.'),
        Q('Detect bias and explain a model\u2019s predictions?',
          ['SageMaker Clarify', 'SageMaker Model Monitor', 'SageMaker Model Cards', 'Amazon Comprehend'],
          'SageMaker Clarify', 'Clarify = bias detection + explainability.'),
        Q('Document a model\u2019s purpose, data and lineage for transparency?',
          ['SageMaker Model Cards', 'SageMaker Model Monitor', 'SageMaker Clarify', 'AWS Artifact'],
          'SageMaker Model Cards', 'Model Cards capture model documentation.'),
        Q('Detect data or quality drift in a deployed model?',
          ['SageMaker Model Monitor', 'SageMaker Clarify', 'Amazon CloudWatch', 'AWS Config'],
          'SageMaker Model Monitor', 'Model Monitor watches production models for drift.'),
        Q('Audit which API calls were made, when and by whom?',
          ['AWS CloudTrail', 'Amazon CloudWatch', 'AWS Config', 'Amazon Inspector'],
          'AWS CloudTrail', 'CloudTrail logs API activity for auditing.'),
        Q('Discover sensitive PII stored in Amazon S3?',
          ['Amazon Macie', 'Amazon Inspector', 'Amazon GuardDuty', 'Amazon Comprehend'],
          'Amazon Macie', 'Macie finds and protects sensitive data in S3.'),
      ],
    },

    {
      id: 'acronyms', name: 'Acronyms', hue: 286,
      blurb: 'Expand the abbreviation.',
      questions: [
        Q('RAG stands for…',
          ['Retrieval Augmented Generation', 'Rapid AI Generation', 'Ranked Answer Grouping', 'Recursive Agent Graph'],
          'Retrieval Augmented Generation', 'RAG retrieves external data to ground an FM.'),
        Q('LLM stands for…',
          ['Large Language Model', 'Layered Learning Machine', 'Logical Language Module', 'Long Latency Model'],
          'Large Language Model', 'LLMs generate and understand text.'),
        Q('FM stands for…',
          ['Foundation Model', 'Functional Model', 'Federated Model', 'Fine-tuned Model'],
          'Foundation Model', 'A large pre-trained model adapted to many tasks.'),
        Q('RLHF stands for…',
          ['Reinforcement Learning from Human Feedback', 'Recurrent Learning of Human Factors', 'Rule-based Learning & Human Filtering', 'Random Loss Heuristic Function'],
          'Reinforcement Learning from Human Feedback', 'RLHF aligns models to human preferences.'),
        Q('NLP stands for…',
          ['Natural Language Processing', 'Neural Logic Programming', 'Network Layer Protocol', 'Native Language Parser'],
          'Natural Language Processing', 'NLP lets machines work with human language.'),
        Q('MCP stands for…',
          ['Model Context Protocol', 'Managed Compute Platform', 'Multi-Cloud Pipeline', 'Model Compression Process'],
          'Model Context Protocol', 'MCP connects agents to external systems.'),
        Q('MLOps refers to…',
          ['Machine Learning Operations', 'Model Lifecycle Optimization', 'Multi-Layer Operations', 'Managed Learning Ops'],
          'Machine Learning Operations', 'Practices to deploy & maintain ML in production.'),
        Q('BLEU is a metric for…',
          ['Translation quality', 'Summarization quality', 'Image quality', 'Classification accuracy'],
          'Translation quality', 'BLEU scores machine translation.'),
        Q('ROUGE is mainly used to evaluate…',
          ['Text summarization', 'Translation', 'Clustering', 'Regression'],
          'Text summarization', 'ROUGE compares a summary to a reference.'),
        Q('The F1 score is…',
          ['The harmonic mean of precision and recall', 'Accuracy divided by recall', 'The area under the ROC curve', 'Mean squared error'],
          'The harmonic mean of precision and recall', 'F1 balances precision and recall.'),
        Q('BERTScore measures…',
          ['Semantic similarity of generated text', 'Number of tokens used', 'Training loss', 'Inference latency'],
          'Semantic similarity of generated text', 'It judges meaning, not exact words.'),
        Q('A2I provides…',
          ['Human-in-the-loop review of predictions', 'Auto-scaling inference', 'API gateway integration', 'Anomaly insights'],
          'Human-in-the-loop review of predictions', 'A2I = Amazon Augmented AI.'),
        Q('AWS KMS manages…',
          ['Encryption keys', 'Access roles', 'Model versions', 'Network routes'],
          'Encryption keys', 'KMS = Key Management Service.'),
        Q('AWS IAM controls…',
          ['Access to AWS resources', 'Model accuracy', 'Inference autoscaling', 'Data ingestion rate'],
          'Access to AWS resources', 'IAM = Identity and Access Management.'),
      ],
    },

    {
      id: 'concepts', name: 'Core Concepts', hue: 150,
      blurb: 'ML & GenAI fundamentals.',
      questions: [
        Q('Labeled training data is used in which learning type?',
          ['Supervised learning', 'Unsupervised learning', 'Reinforcement learning', 'Self-supervised learning'],
          'Supervised learning', 'Labels → supervised (classification, regression).'),
        Q('Grouping unlabeled data into segments is…',
          ['Clustering (unsupervised)', 'Classification', 'Regression', 'Reinforcement learning'],
          'Clustering (unsupervised)', 'No labels + grouping = unsupervised clustering.'),
        Q('Learning from rewards and penalties is…',
          ['Reinforcement learning', 'Supervised learning', 'Unsupervised learning', 'Transfer learning'],
          'Reinforcement learning', 'Reward signal → reinforcement (also RLHF).'),
        Q('Predicting a continuous number (e.g. a price) is…',
          ['Regression', 'Classification', 'Clustering', 'Ranking'],
          'Regression', 'Regression predicts a quantity; classification predicts a label.'),
        Q('A model that is too simple and underfits has…',
          ['High bias', 'High variance', 'Low bias', 'No error'],
          'High bias', 'High bias = underfitting.'),
        Q('A model that memorizes the training data has…',
          ['High variance (overfitting)', 'High bias', 'Underfitting', 'Low variance'],
          'High variance (overfitting)', 'High variance = overfitting.'),
        Q('Raising an LLM\u2019s temperature makes output…',
          ['More random and creative', 'More deterministic', 'Shorter', 'More factual'],
          'More random and creative', 'Higher temperature = more randomness.'),
        Q('The cheapest, least-effort way to customize an FM is…',
          ['Prompt engineering', 'Fine-tuning', 'Continued pre-training', 'Pre-training from scratch'],
          'Prompt engineering', 'Prompt engineering needs no training.'),
        Q('Which is the MOST expensive way to customize an FM?',
          ['Pre-training from scratch', 'Prompt engineering', 'RAG', 'Fine-tuning'],
          'Pre-training from scratch', 'The top of the cost ladder.'),
        Q('Which approach grounds an FM in your own documents?',
          ['RAG', 'Raising temperature', 'Fine-tuning the tokenizer', 'Quantization'],
          'RAG', 'RAG retrieves your data to reduce hallucination.'),
        Q('Which metric set evaluates generated text (not classifiers)?',
          ['ROUGE, BLEU, BERTScore', 'Accuracy, precision, recall', 'RMSE and MAE', 'Silhouette score'],
          'ROUGE, BLEU, BERTScore', 'These judge generated language.'),
        Q('Few-shot prompting means…',
          ['Giving a few examples inside the prompt', 'Training on a few samples', 'Using a small model', 'Running a few epochs'],
          'Giving a few examples inside the prompt', 'Examples in-context, no training.'),
        Q('Chain-of-thought prompting encourages the model to…',
          ['Show step-by-step reasoning', 'Use fewer tokens', 'Avoid examples', 'Lower its temperature'],
          'Show step-by-step reasoning', 'CoT elicits intermediate reasoning steps.'),
        Q('GenAI sits inside which nesting?',
          ['AI ⊃ ML ⊃ Deep Learning ⊃ GenAI', 'ML ⊃ AI ⊃ GenAI', 'GenAI ⊃ AI ⊃ ML', 'AI ⊃ GenAI ⊃ ML'],
          'AI ⊃ ML ⊃ Deep Learning ⊃ GenAI', 'GenAI is a subset of deep learning.'),
      ],
    },

    {
      id: 'patterns', name: 'Scenarios & Responsible AI', hue: 24,
      blurb: 'Pick the right answer for the situation.',
      questions: [
        Q('A bank needs an explainable, auditable model for loan approvals. Choose…',
          ['Traditional ML', 'A large foundation model', 'A RAG chatbot', 'A diffusion model'],
          'Traditional ML', 'Regulatory / explainability needs favor traditional ML.'),
        Q('You must stop a chatbot from producing hateful content. Use…',
          ['Bedrock Guardrails', 'SageMaker Clarify', 'Amazon Macie', 'AWS IAM'],
          'Bedrock Guardrails', 'Guardrails filter harmful output.'),
        Q('Support answers must cite your internal docs. Best approach…',
          ['RAG with Bedrock Knowledge Bases', 'Pre-train a new model', 'Raise the temperature', 'Use Amazon Polly'],
          'RAG with Bedrock Knowledge Bases', 'RAG grounds answers in your data.'),
        Q('Under the shared responsibility model, who secures the data you put in S3?',
          ['The customer', 'AWS', 'AWS and the customer equally', 'The AWS Region'],
          'The customer', 'Customer secures in the cloud; AWS secures the cloud.'),
        Q('Which Well-Architected concern covers fairness and bias mitigation?',
          ['Responsible AI', 'Operational excellence', 'Cost optimization', 'Performance efficiency'],
          'Responsible AI', 'Fairness, safety and veracity are Responsible-AI pillars.'),
        Q('You want the least-effort tweak to an FM\u2019s tone. Start with…',
          ['Prompt engineering', 'Continued pre-training', 'Training a new model', 'RLHF'],
          'Prompt engineering', 'Always try prompting before training.'),
        Q('Where do you store vector embeddings for RAG?',
          ['Amazon OpenSearch Service', 'Amazon DynamoDB', 'Amazon S3 Glacier', 'Amazon CloudFront'],
          'Amazon OpenSearch Service', 'Vector DBs: OpenSearch, Aurora, Neptune, RDS for PostgreSQL.'),
        Q('Unlabeled customer data, and you want to find natural groups. Use…',
          ['Unsupervised clustering', 'Supervised classification', 'Reinforcement learning', 'Regression'],
          'Unsupervised clustering', 'No labels + grouping = unsupervised.'),
        Q('Translate a live chat between English and Japanese. Use…',
          ['Amazon Translate', 'Amazon Transcribe', 'Amazon Comprehend', 'Amazon Polly'],
          'Amazon Translate', 'Translate handles language translation.'),
        Q('Add captions to recorded webinars. Use…',
          ['Amazon Transcribe', 'Amazon Polly', 'Amazon Lex', 'Amazon Kendra'],
          'Amazon Transcribe', 'Transcribe converts the audio to text.'),
        Q('Classify product reviews as positive or negative. Use…',
          ['Amazon Comprehend', 'Amazon Rekognition', 'Amazon Personalize', 'Amazon Q'],
          'Amazon Comprehend', 'Comprehend does sentiment analysis.'),
        Q('Document model details for a transparency audit. Use…',
          ['SageMaker Model Cards', 'SageMaker Model Monitor', 'AWS CloudTrail', 'Bedrock Guardrails'],
          'SageMaker Model Cards', 'Model Cards record lineage and details.'),
      ],
    },
  ];

  // ═══════════════ EXPANSION ═══════════════
  // Net-new questions appended per category. Multiple-response questions use a
  // `correct` array; single-answer questions a string. Each sets `diff`.
  const EXTRA = {
    services: [
      Q('Which service is AWS’s generative AI coding assistant for developers?',
        ['Amazon Q Developer', 'Amazon Q Business', 'Amazon Comprehend', 'Amazon Kendra'],
        'Amazon Q Developer', 'Q Developer generates code and helps inside the IDE.', 'easy'),
      Q('Which service answers questions from your enterprise data with citations?',
        ['Amazon Q Business', 'Amazon Q Developer', 'Amazon Polly', 'Amazon Translate'],
        'Amazon Q Business', 'Q Business is a permissions-aware assistant over company data.', 'easy'),
      Q('Which serverless service runs and scales AI agents in production?',
        ['Amazon Bedrock AgentCore', 'Amazon Bedrock Guardrails', 'SageMaker Clarify', 'Amazon Macie'],
        'Amazon Bedrock AgentCore', 'AgentCore provides runtime, memory and identity for agents.', 'intermediate'),
      Q('Which Bedrock capability transfers a large model’s knowledge into a smaller, cheaper model?',
        ['Model distillation', 'Prompt management', 'Guardrails', 'Knowledge Bases'],
        'Model distillation', 'Distillation trains a small student to mimic a large teacher.', 'advanced'),
      Q('Which service builds and secures a data lake with fine-grained permissions?',
        ['AWS Lake Formation', 'Amazon EMR', 'Amazon CloudFront', 'AWS Budgets'],
        'AWS Lake Formation', 'Lake Formation centralises data-lake access control.', 'intermediate'),
      Q('Which service offers visual, no-code data preparation?',
        ['AWS Glue DataBrew', 'AWS Glue', 'Amazon Redshift', 'Amazon Athena'],
        'AWS Glue DataBrew', 'DataBrew cleans and transforms data through a visual UI.', 'intermediate'),
      Q('Which service provides serverless ETL and a data catalog?',
        ['AWS Glue', 'Amazon QuickSight', 'Amazon Neptune', 'AWS Artifact'],
        'AWS Glue', 'Glue runs serverless extract-transform-load pipelines.', 'easy'),
      Q('Where should you store and automatically rotate API keys and credentials?',
        ['AWS Secrets Manager', 'Amazon S3', 'AWS Config', 'Amazon CloudWatch'],
        'AWS Secrets Manager', 'Secrets Manager stores and rotates secrets securely.', 'easy'),
      Q('Which service sets cost budgets and alerts you when spend is exceeded?',
        ['AWS Budgets', 'AWS Cost Explorer', 'AWS Trusted Advisor', 'Amazon CloudWatch'],
        'AWS Budgets', 'Budgets tracks spend against thresholds and alerts.', 'easy'),
      Q('Which service is commonly used as a vector store for RAG embeddings?',
        ['Amazon OpenSearch Service', 'Amazon S3 Glacier', 'Amazon CloudFront', 'AWS Lambda'],
        'Amazon OpenSearch Service', 'OpenSearch is a popular managed vector database.', 'intermediate'),
      Q('Which service produces time-series forecasts from historical data?',
        ['Amazon Forecast', 'Amazon Personalize', 'Amazon Comprehend', 'Amazon Lex'],
        'Amazon Forecast', 'Forecast predicts future values from time-series data.', 'advanced'),
      Q('Which managed service detects potentially fraudulent online activity?',
        ['Amazon Fraud Detector', 'Amazon Macie', 'Amazon Inspector', 'Amazon GuardDuty'],
        'Amazon Fraud Detector', 'Fraud Detector scores the risk of fraud with ML.', 'advanced'),
      Q('Which service creates labeled training datasets using human annotators?',
        ['SageMaker Ground Truth', 'SageMaker Clarify', 'SageMaker Model Monitor', 'Amazon A2I'],
        'SageMaker Ground Truth', 'Ground Truth labels data for supervised learning.', 'advanced'),
      Q('Which service lets a business analyst build ML models with no code?',
        ['SageMaker Canvas', 'SageMaker JumpStart', 'SageMaker Pipelines', 'Amazon Bedrock'],
        'SageMaker Canvas', 'Canvas is a no-code ML interface for analysts.', 'advanced'),
      Q('Which AWS chip is purpose-built to accelerate model training?',
        ['AWS Trainium', 'AWS Inferentia', 'Amazon EC2', 'AWS Lambda'],
        'AWS Trainium', 'Trainium accelerates training; Inferentia accelerates inference.', 'advanced'),
      Q('Which service delivers content to users with low latency via a CDN?',
        ['Amazon CloudFront', 'Amazon VPC', 'Amazon S3 Glacier', 'AWS PrivateLink'],
        'Amazon CloudFront', 'CloudFront is AWS’s content delivery network.', 'easy'),
      Q('Which service is durable object storage for datasets and model artefacts?',
        ['Amazon S3', 'Amazon EBS', 'Amazon ElastiCache', 'Amazon DocumentDB'],
        'Amazon S3', 'S3 is the default object store on AWS.', 'easy'),
      Q('Which service runs code without provisioning servers?',
        ['AWS Lambda', 'Amazon EC2', 'Amazon ECS', 'Amazon EMR'],
        'AWS Lambda', 'Lambda runs functions serverlessly, billed per use.', 'easy'),
      Q('Which tool reviews a workload against AWS best practices, including a GenAI lens?',
        ['AWS Well-Architected Tool', 'AWS Trusted Advisor', 'AWS Config', 'AWS Audit Manager'],
        'AWS Well-Architected Tool', 'The Well-Architected Tool guides best-practice reviews.', 'intermediate'),
      Q('Which agentic AI service modernises and migrates legacy workloads with human review?',
        ['AWS Transform', 'Amazon Bedrock', 'Amazon Q Business', 'AWS Glue'],
        'AWS Transform', 'AWS Transform automates mainframe, VMware and .NET modernisation.', 'intermediate'),
      Q('Which open-source SDK is used to build autonomous AI agents on AWS?',
        ['Strands Agents', 'Amazon Personalize', 'Amazon Kendra', 'AWS Glue DataBrew'],
        'Strands Agents', 'Strands is a code-first framework for tool-using agents.', 'intermediate'),
      Q('Which big-data service runs Apache Spark and Hadoop workloads?',
        ['Amazon EMR', 'Amazon Redshift', 'Amazon Athena', 'Amazon Neptune'],
        'Amazon EMR', 'EMR processes very large datasets with Spark/Hadoop.', 'intermediate'),
      Q('Where do you find and subscribe to third-party datasets on AWS?',
        ['AWS Data Exchange', 'AWS Lake Formation', 'Amazon QuickSight', 'AWS Artifact'],
        'AWS Data Exchange', 'Data Exchange offers third-party data subscriptions.', 'intermediate'),
      Q('Which service is a unified business-intelligence platform with AI analytics agents?',
        ['Amazon Quick Suite', 'Amazon Comprehend', 'Amazon Kendra', 'AWS Glue'],
        'Amazon Quick Suite', 'Quick Suite combines dashboards with AI analytics.', 'intermediate'),
      Q('Select the AWS managed AI services for working with language. (Select THREE.)',
        ['Amazon Comprehend', 'Amazon Translate', 'Amazon Transcribe', 'Amazon EC2', 'Amazon S3'],
        ['Amazon Comprehend', 'Amazon Translate', 'Amazon Transcribe'],
        'Comprehend (NLP), Translate (translation) and Transcribe (speech-to-text) are language services; EC2 and S3 are infrastructure.', 'advanced'),
      Q('Which services can act as a vector store for embeddings? (Select THREE.)',
        ['Amazon OpenSearch Service', 'Amazon Aurora (PostgreSQL)', 'Amazon Neptune', 'Amazon CloudFront', 'Amazon S3 Glacier'],
        ['Amazon OpenSearch Service', 'Amazon Aurora (PostgreSQL)', 'Amazon Neptune'],
        'OpenSearch, Aurora PostgreSQL (pgvector) and Neptune can store vectors; CloudFront and Glacier cannot.', 'advanced'),
    ],

    acronyms: [
      Q('CoT stands for…',
        ['Chain-of-Thought', 'Context-of-Tokens', 'Cost-of-Training', 'Cache-on-Throughput'],
        'Chain-of-Thought', 'CoT prompts the model to reason step by step.', 'easy'),
      Q('HITL stands for…',
        ['Human-in-the-Loop', 'High-Inference Test Layer', 'Hybrid Inference Training Loop', 'Human Input Tagging Library'],
        'Human-in-the-Loop', 'A person reviews or approves model output.', 'easy'),
      Q('PII stands for…',
        ['Personally Identifiable Information', 'Private Internal Index', 'Predicted Inference Interval', 'Public Identity Indicator'],
        'Personally Identifiable Information', 'Sensitive personal data that must be protected.', 'easy'),
      Q('ETL stands for…',
        ['Extract, Transform, Load', 'Evaluate, Test, Launch', 'Encode, Tokenize, Learn', 'Export, Train, Log'],
        'Extract, Transform, Load', 'The pipeline that prepares raw data.', 'easy'),
      Q('ARPU stands for…',
        ['Average Revenue Per User', 'Annual Rate of Prediction Updates', 'Aggregate Recall Per Unit', 'Adjusted Ratio of Precision and Usage'],
        'Average Revenue Per User', 'A GenAI business value metric.', 'easy'),
      Q('CLV stands for…',
        ['Customer Lifetime Value', 'Cross-Lingual Vector', 'Continuous Learning Validation', 'Class Label Variance'],
        'Customer Lifetime Value', 'Total expected revenue from a customer.', 'easy'),
      Q('In AWS, EC2 stands for…',
        ['Elastic Compute Cloud', 'Encrypted Container Cluster', 'Edge Compute Controller', 'Enterprise Cloud Connector'],
        'Elastic Compute Cloud', 'EC2 provides virtual servers.', 'easy'),
      Q('In AWS, S3 stands for…',
        ['Simple Storage Service', 'Secure Streaming Service', 'Scalable Search Service', 'Structured Storage System'],
        'Simple Storage Service', 'S3 is object storage.', 'easy'),
      Q('VPC stands for…',
        ['Virtual Private Cloud', 'Vector Processing Core', 'Validated Prompt Cache', 'Versioned Pipeline Config'],
        'Virtual Private Cloud', 'An isolated private network on AWS.', 'easy'),
      Q('OCR stands for…',
        ['Optical Character Recognition', 'Output Confidence Rating', 'Online Content Retrieval', 'Ordered Class Ranking'],
        'Optical Character Recognition', 'Turns text in images into machine-readable text.', 'easy'),
    ],

    concepts: [
      Q('Token-based pricing means inference cost scales mainly with…',
        ['The number of input and output tokens', 'The number of users', 'The model’s training cost', 'The storage used'],
        'The number of input and output tokens', 'You pay per token processed.', 'intermediate'),
      Q('Embeddings are best described as…',
        ['Numeric vectors that capture meaning', 'Compressed image files', 'Encrypted API keys', 'Model training logs'],
        'Numeric vectors that capture meaning', 'Similar items sit close in vector space.', 'intermediate'),
      Q('Why are long documents chunked before being embedded for RAG?',
        ['To fit context limits and improve retrieval', 'To encrypt them', 'To translate them', 'To reduce token pricing to zero'],
        'To fit context limits and improve retrieval', 'Right-sized chunks retrieve more relevant passages.', 'easy'),
      Q('Diffusion models are typically used to generate…',
        ['Images', 'Spreadsheets', 'SQL queries', 'Network routes'],
        'Images', 'Diffusion underlies text-to-image generation.', 'easy'),
      Q('A multi-modal model is one that…',
        ['Handles more than one data type, such as text and images', 'Runs in multiple Regions', 'Uses multiple GPUs', 'Has multiple owners'],
        'Handles more than one data type, such as text and images', 'Multi-modal spans text, image, audio, etc.', 'easy'),
      Q('Context engineering refers to…',
        ['Designing what information goes into the model’s context window', 'Tuning GPU clusters', 'Compressing model weights', 'Encrypting prompts'],
        'Designing what information goes into the model’s context window', 'It controls the data, instructions and history supplied.', 'intermediate'),
      Q('What is the role of the Model Context Protocol (MCP)?',
        ['A standard way to connect agents to external tools and data', 'A method to compress models', 'A pricing model for tokens', 'A type of neural network'],
        'A standard way to connect agents to external tools and data', 'MCP standardises agent-to-system connections.', 'intermediate'),
      Q('The biggest reliability risk to plan for with GenAI is…',
        ['Hallucination (confident but wrong output)', 'Slow disk I/O', 'Running out of IP addresses', 'Excessive logging'],
        'Hallucination (confident but wrong output)', 'Models can state false information convincingly.', 'intermediate'),
      Q('"Nondeterminism" in GenAI means…',
        ['The same prompt can produce different outputs', 'The model never changes its answer', 'Outputs are always encrypted', 'Training data is random'],
        'The same prompt can produce different outputs', 'Sampling makes responses vary.', 'intermediate'),
      Q('Which customization approach trains a small model to mimic a large one?',
        ['Model distillation', 'Prompt engineering', 'RAG', 'Quantization of the tokenizer'],
        'Model distillation', 'Distillation yields a cheaper, faster student model.', 'advanced'),
      Q('In-context learning works by…',
        ['Providing examples in the prompt, with no training', 'Retraining the model weights', 'Adding more GPUs', 'Lowering temperature to zero'],
        'Providing examples in the prompt, with no training', 'Few-shot examples steer behaviour at inference time.', 'easy'),
      Q('Provisioned throughput in Amazon Bedrock is best for…',
        ['Steady, high-volume workloads needing guaranteed capacity', 'One-off experiments', 'Reducing model accuracy', 'Disabling guardrails'],
        'Steady, high-volume workloads needing guaranteed capacity', 'It reserves capacity versus pay-per-use on-demand.', 'advanced'),
      Q('RLHF improves a model by…',
        ['Aligning outputs to human preference feedback', 'Adding more storage', 'Encrypting the weights', 'Increasing the token price'],
        'Aligning outputs to human preference feedback', 'Reinforcement learning from human feedback aligns behaviour.', 'intermediate'),
      Q('"LLM-as-a-judge" evaluation means…',
        ['Using a strong model to score another model’s outputs', 'Letting the model set its own price', 'Having the model write its own prompts', 'Running the model on a judge’s laptop'],
        'Using a strong model to score another model’s outputs', 'It scales evaluation beyond human review.', 'intermediate'),
      Q('Which data type best suits demand forecasting?',
        ['Time-series data', 'Image data', 'Audio data', 'Graph data'],
        'Time-series data', 'Forecasting predicts future values over time.', 'intermediate'),
      Q('When is an AI/ML solution usually NOT appropriate?',
        ['When an exact, guaranteed outcome is required', 'When data is plentiful', 'When patterns are complex', 'When scale is needed'],
        'When an exact, guaranteed outcome is required', 'Use deterministic rules when predictions are unacceptable.', 'intermediate'),
      Q('Using a managed API service (e.g. Amazon Bedrock) instead of self-hosting trades…',
        ['Less control for less operational effort', 'Lower accuracy for higher cost', 'More servers for fewer features', 'Security for speed'],
        'Less control for less operational effort', 'Managed services remove infrastructure work.', 'intermediate'),
      Q('The final stage of the AI/ML lifecycle is typically…',
        ['Monitoring (and retraining) the deployed model', 'Data collection', 'Model selection', 'Feature scaling'],
        'Monitoring (and retraining) the deployed model', 'Production models are watched for drift.', 'intermediate'),
      Q('The main goal of MLOps is…',
        ['Repeatable, scalable, monitored ML in production', 'Writing model math by hand', 'Eliminating all cloud costs', 'Avoiding version control'],
        'Repeatable, scalable, monitored ML in production', 'MLOps operationalises the ML lifecycle.', 'intermediate'),
      Q('Which is a common source of a foundation model?',
        ['An open-source pre-trained model', 'A spreadsheet macro', 'A CDN edge cache', 'A load balancer'],
        'An open-source pre-trained model', 'Teams often start from pre-trained FMs.', 'intermediate'),
      Q('Which of these are features of responsible AI? (Select THREE.)',
        ['Fairness', 'Safety', 'Veracity', 'Lower token price', 'Faster GPUs'],
        ['Fairness', 'Safety', 'Veracity'],
        'Fairness, safety and veracity are responsible-AI features; price and hardware are not.', 'advanced'),
      Q('A key legal risk of generative AI is…',
        ['Intellectual property infringement', 'Running out of storage', 'Slow network throughput', 'Too many log files'],
        'Intellectual property infringement', 'Generated content may copy protected work.', 'advanced'),
      Q('Which dataset qualities most reduce bias?',
        ['Diverse, balanced and curated data', 'The largest possible file size', 'Data from a single source', 'Only recent data'],
        'Diverse, balanced and curated data', 'Representative data reduces unfair outcomes.', 'intermediate'),
      Q('A sustainability-minded model choice is to…',
        ['Prefer a smaller, efficient model that still meets the need', 'Always use the largest model', 'Train from scratch every time', 'Disable caching'],
        'Prefer a smaller, efficient model that still meets the need', 'Smaller models cut energy and cost.', 'intermediate'),
      Q('Which tool detects bias and explains model predictions?',
        ['SageMaker Clarify', 'SageMaker Model Monitor', 'Amazon Macie', 'AWS Config'],
        'SageMaker Clarify', 'Clarify covers bias detection and explainability.', 'intermediate'),
      Q('Human-centred design for explainable AI emphasises…',
        ['User feedback mechanisms and clear decision transparency', 'Hiding how decisions are made', 'Maximising model size', 'Removing all human input'],
        'User feedback mechanisms and clear decision transparency', 'It designs XAI around the people using it.', 'intermediate'),
      Q('The interpretability-versus-performance tradeoff means…',
        ['More accurate models are often harder to explain', 'Faster models are always fairer', 'Bigger data always means clarity', 'Explainable models cannot be accurate'],
        'More accurate models are often harder to explain', 'You balance accuracy against explainability.', 'advanced'),
      Q('Encryption in transit is provided by…',
        ['TLS', 'A confusion matrix', 'A vector database', 'Chain-of-thought'],
        'TLS', 'TLS protects data moving over the network.', 'intermediate'),
      Q('Encryption at rest on AWS is commonly managed with…',
        ['AWS KMS keys', 'Amazon CloudFront', 'Amazon Lex', 'AWS Budgets'],
        'AWS KMS keys', 'KMS manages keys that encrypt stored data.', 'intermediate'),
      Q('Prompt injection is…',
        ['Malicious input that overrides the model’s instructions', 'A way to speed up inference', 'A method to label data', 'A pricing tier'],
        'Malicious input that overrides the model’s instructions', 'Untrusted input hijacks the prompt.', 'intermediate'),
      Q('Which measures help mitigate prompt injection? (Select THREE.)',
        ['Guardrails', 'Input validation', 'Least-privilege access', 'Raising the temperature', 'Using a larger model'],
        ['Guardrails', 'Input validation', 'Least-privilege access'],
        'Guardrails, validation and least privilege reduce injection risk; temperature and model size do not.', 'advanced'),
      Q('Source citation and data lineage for a model are documented with…',
        ['SageMaker Model Cards', 'Amazon CloudFront', 'AWS Lambda', 'Amazon SQS'],
        'SageMaker Model Cards', 'Model Cards record data origins and intended use.', 'intermediate'),
      Q('Which belong to a data governance strategy? (Select THREE.)',
        ['Data retention', 'Data residency', 'Data lifecycle management', 'Higher temperature', 'More tokens'],
        ['Data retention', 'Data residency', 'Data lifecycle management'],
        'Retention, residency and lifecycle are governance concerns; inference settings are not.', 'advanced'),
      Q('Which governance framework helps scope a GenAI application’s security?',
        ['Generative AI Security Scoping Matrix', 'BLEU score', 'Leitner system', 'Confusion matrix'],
        'Generative AI Security Scoping Matrix', 'It classifies GenAI use by ownership and risk.', 'advanced'),
      Q('Which techniques reduce hallucinations? (Select THREE.)',
        ['RAG grounding', 'Output validation', 'Confidence scoring', 'Raising the temperature', 'Adding more output tokens'],
        ['RAG grounding', 'Output validation', 'Confidence scoring'],
        'Grounding, validation and confidence scoring improve accuracy; higher temperature increases randomness.', 'advanced'),
      Q('Order the FM customization approaches from LOWEST to HIGHEST cost. Which sequence is correct?',
        ['Prompt engineering → RAG → Fine-tuning → Pre-training from scratch', 'RAG → Prompt engineering → Pre-training → Fine-tuning', 'Fine-tuning → RAG → Prompt engineering → Pre-training', 'Pre-training → Fine-tuning → RAG → Prompt engineering'],
        'Prompt engineering → RAG → Fine-tuning → Pre-training from scratch', 'Cost climbs from prompting up to pre-training from scratch.', 'advanced'),
      Q('Order SageMaker inference options from LOWEST to HIGHEST latency. Which is correct?',
        ['Real-time → Asynchronous → Batch transform', 'Batch transform → Real-time → Asynchronous', 'Asynchronous → Batch transform → Real-time', 'Batch transform → Asynchronous → Real-time'],
        'Real-time → Asynchronous → Batch transform', 'Real-time is lowest latency; batch is highest.', 'advanced'),
    ],

    patterns: [
      Q('You must reduce hallucinations by grounding answers in your own current documents, without training. Use…',
        ['RAG with Bedrock Knowledge Bases', 'Pre-training from scratch', 'Raising the temperature', 'Amazon Polly'],
        'RAG with Bedrock Knowledge Bases', 'RAG retrieves your data at query time.', 'intermediate'),
      Q('You need to bake your product catalogue and house tone into the model itself. Use…',
        ['Fine-tuning', 'Prompt engineering only', 'A CDN', 'Higher temperature'],
        'Fine-tuning', 'Fine-tuning changes the model’s behaviour for your domain.', 'intermediate'),
      Q('A regulated loan decision must be explainable and auditable. Choose…',
        ['Traditional ML with SageMaker Clarify', 'A large foundation model with high temperature', 'A diffusion model', 'A RAG chatbot'],
        'Traditional ML with SageMaker Clarify', 'Explainability favours traditional ML; Clarify explains it.', 'advanced'),
      Q('You need a system that plans multi-step tasks, remembers context and calls tools. Build…',
        ['An AI agent (e.g. with Bedrock AgentCore)', 'A single prompt', 'A static FAQ page', 'A batch ETL job'],
        'An AI agent (e.g. with Bedrock AgentCore)', 'Agents plan, remember and act via tools.', 'advanced'),
      Q('A live chatbot needs the lowest-latency responses. Choose which inference type?',
        ['Real-time inference', 'Batch transform', 'Asynchronous inference', 'Scheduled inference'],
        'Real-time inference', 'Real-time serves interactive, low-latency requests.', 'intermediate'),
      Q('You must score millions of records overnight, latency is not a concern. Use…',
        ['Batch inference', 'Real-time inference', 'Provisioned throughput chat', 'A guardrail'],
        'Batch inference', 'Batch is cost-effective for large offline jobs.', 'intermediate'),
      Q('You want guaranteed model capacity for a steady production workload. Use…',
        ['Provisioned throughput', 'On-demand only', 'A larger temperature', 'A bigger context window'],
        'Provisioned throughput', 'Provisioned throughput reserves capacity.', 'advanced'),
      Q('A long system prompt is reused on every request and is costly. Reduce cost with…',
        ['Prompt caching', 'A new model each call', 'Higher temperature', 'More output tokens'],
        'Prompt caching', 'Caching reuses the prompt prefix to cut cost and latency.', 'advanced'),
      Q('You must keep model traffic off the public internet. Use…',
        ['AWS PrivateLink within a VPC', 'Amazon CloudFront', 'A public S3 bucket', 'Amazon SNS'],
        'AWS PrivateLink within a VPC', 'PrivateLink keeps service traffic private.', 'intermediate'),
      Q('Which controls help secure an AI system? (Select THREE.)',
        ['IAM least-privilege roles', 'Encryption with KMS', 'Bedrock Guardrails', 'Raising the temperature', 'Adding more output tokens'],
        ['IAM least-privilege roles', 'Encryption with KMS', 'Bedrock Guardrails'],
        'Access control, encryption and guardrails secure AI; inference settings do not.', 'advanced'),
      Q('Which are responsible-AI tools on AWS? (Select THREE.)',
        ['SageMaker Clarify', 'Amazon A2I', 'Bedrock Guardrails', 'Amazon CloudFront', 'Amazon S3 Glacier'],
        ['SageMaker Clarify', 'Amazon A2I', 'Bedrock Guardrails'],
        'Clarify, A2I and Guardrails support responsible AI; CloudFront and Glacier are infrastructure.', 'advanced'),
      Q('You must record who invoked the model API and when. Use…',
        ['AWS CloudTrail', 'Amazon CloudWatch metrics only', 'AWS Budgets', 'Amazon Macie'],
        'AWS CloudTrail', 'CloudTrail logs API activity for auditing.', 'intermediate'),
      Q('You need continuous evidence collection for an audit. Use…',
        ['AWS Audit Manager', 'AWS Artifact', 'Amazon Inspector', 'AWS Config'],
        'AWS Audit Manager', 'Audit Manager automates audit evidence collection.', 'intermediate'),
      Q('Your auditor needs AWS’s SOC and ISO compliance reports. Get them from…',
        ['AWS Artifact', 'AWS Audit Manager', 'Amazon Macie', 'Amazon CloudWatch'],
        'AWS Artifact', 'Artifact provides on-demand compliance reports.', 'intermediate'),
      Q('You must be alerted when an S3 bucket becomes publicly readable. Use…',
        ['AWS Config', 'AWS CloudTrail', 'Amazon Inspector', 'Amazon Comprehend'],
        'AWS Config', 'Config flags non-compliant resource configurations.', 'intermediate'),
      Q('Which factors should drive choosing a GenAI model? (Select THREE.)',
        ['Cost', 'Latency', 'Modality and compliance needs', 'The card colour in the UI', 'The number of vowels in its name'],
        ['Cost', 'Latency', 'Modality and compliance needs'],
        'Cost, latency, modality and compliance are real selection factors.', 'advanced'),
      Q('You need to translate a live chat between English and Japanese. Use…',
        ['Amazon Translate', 'Amazon Transcribe', 'Amazon Comprehend', 'Amazon Polly'],
        'Amazon Translate', 'Translate handles language translation.', 'easy'),
      Q('You need to add captions to recorded webinars. Use…',
        ['Amazon Transcribe', 'Amazon Polly', 'Amazon Lex', 'Amazon Kendra'],
        'Amazon Transcribe', 'Transcribe converts speech to text.', 'easy'),
      Q('You need product recommendations like Amazon.com. Use…',
        ['Amazon Personalize', 'Amazon Forecast', 'Amazon Rekognition', 'Amazon Q'],
        'Amazon Personalize', 'Personalize builds recommendation systems.', 'easy'),
      Q('Low-confidence predictions should be sent to a person to review. Use…',
        ['Amazon A2I', 'SageMaker Clarify', 'Bedrock Guardrails', 'AWS Config'],
        'Amazon A2I', 'A2I adds human-in-the-loop review.', 'intermediate'),
      Q('You want to compare two foundation models on your own prompts. Use…',
        ['Bedrock Model Evaluation', 'Bedrock Guardrails', 'SageMaker Model Monitor', 'AWS Artifact'],
        'Bedrock Model Evaluation', 'Model Evaluation compares FM performance.', 'intermediate'),
      Q('You need to scope a new GenAI app’s security responsibilities and risk. Use…',
        ['The Generative AI Security Scoping Matrix', 'A confusion matrix', 'A BLEU score', 'A Leitner box'],
        'The Generative AI Security Scoping Matrix', 'It classifies GenAI use to decide controls.', 'advanced'),
    ],
  };

  // Every question carries a difficulty. New questions set it explicitly; the
  // rest default by category. Also append the expansion questions per category.
  const DEF = { services: 'easy', acronyms: 'easy', concepts: 'intermediate', patterns: 'intermediate' };
  for (const cat of categories) {
    if (EXTRA[cat.id]) cat.questions.push(...EXTRA[cat.id]);
    for (const qq of cat.questions) if (!qq.diff) qq.diff = DEF[cat.id] || 'intermediate';
  }

  return { categories };
})();
